### PR TITLE
fix: decompress deltelog path for level zero compaction

### LINKED ISSUE #30161: [Bug]: l0 compaction task binlog is not decompressed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: ae4f62a
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Binlog paths are compressed into log id in datacoord memory. For level zero compaction, the binlog is not decompressed before sending task to datanode

### Expected Behavior

Datanode get complete task info for all 

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Resolves: #30161
See also: #28873

### CODE REVIEW

File: internal/datacoord/compaction_trigger_v2.go [hunk 1]
```diff
@@ -91,9 +93,11 @@ func (m *CompactionTriggerManager) BuildLevelZeroCompactionPlan(view CompactionV
 	var segmentBinlogs []*datapb.CompactionSegmentBinlogs
 	levelZeroSegs := lo.Map(view.GetSegmentsView(), func(v *SegmentView, _ int) *datapb.CompactionSegmentBinlogs {
 		s := m.meta.GetSegment(v.ID)
+		cloned := s.Clone()
+		binlog.DecompressBinLog(storage.DeleteBinlog, cloned.GetCollectionID(), cloned.GetPartitionID(), cloned.GetID(), cloned.GetDeltalogs())
```
Comment (smellthemoon) [inline internal/datacoord/compaction_trigger_v2.go:97]: DecompressBinLog in dn(compact func in internal/datanode/l0_compactor.go) may be more suitable, since dc not use path anymore.
