### PR TITLE
Fix Cgo lock os thread failed

### LINKED ISSUE #19147: [Bug]: Create too many Os thread because of Cgo blocked
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We create a pool with a bunch a go routine locked with OS thread, so root thread of openmp is always limited.

But for some concurrency reason,  not all go routine is locked as expected.

### Expected Behavior

Fix all concurrency issues, make sure every go routine in the cgo pool is locked as expect

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xiaofan-luan**
fix #19147 
Signed-off-by: xiaofan-luan <xiaofan.luan@zilliz.com>

### CODE REVIEW

File: internal/querynode/query_node.go [hunk 1]
```diff
@@ -240,15 +240,20 @@ func (node *QueryNode) Init() error {
 			return
 		}
 
+		// ensure every cgopool go routine is locked with a OS thread
+		// so openmp in knowhere won't create too much request
 		sig := make(chan struct{})
```
Comment (jiaoew1991) [inline internal/querynode/query_node.go:245]: Is sig still useful with WaitGroup？

**Review by congqixia — APPROVED** [review]
/lgtm
