### PR TITLE
Fix DropCollection not processed by datanode

### LINKED ISSUE #6999: Datanode flowgraph not closed caused by missing DropCollection
After a smoke test, datanode still has hundreds of goroutines running, most of the which are serving `flowgraph`. The datanode instance still consumes lots of CPU which it should not.

The obvious phenomenon is that the related `DropCollection` message is not received.
 
One of the possible reason is #6988

### PR DESCRIPTION
**Pull request by congqixia**
Add cleanup for DropCollection related pchan

Fix: #6999 

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

### CODE REVIEW

File: internal/rootcoord/dml_channels.go [hunk 1]
```diff
@@ -133,22 +116,17 @@ func (d *dmlChannels) AddProducerChannels(names ...string) {
...
 func (d *dmlChannels) RemoveProducerChannels(names ...string) {
 	d.lock.Lock()
 	defer d.lock.Unlock()
 
 	for _, name := range names {
-		//log.Debug("delete dml channel", zap.String("channel name", name))
-		if ds, ok := d.dml[name]; ok {
-			ds.valid = false
-		}
+		delete(d.dml, name)
```
Comment (cydrain) [inline internal/rootcoord/dml_channels.go:130]: why not do msgStream close here ?
