### PR TITLE
Fix #18872 milvus crahsed when inserting empty string

### LINKED ISSUE #18872: [Bug]: Milvus crashed when inserting empty string for varchar field
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.1
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Milvus crashed when inserting empty string for varchar field.

The crash log:
```
[2022/08/29 02:44:56.850 +00:00] [INFO] [datacoord/services.go:1019] ["[flush state] unflushed segment ids"] [segmentIDs="[435615456365903873,435615456365903874]"] [len=2]
[2022/08/29 02:44:56.850 +00:00] [INFO] [proxy/impl.go:3585] ["received get flush state response"] [response="status:<> "]
[2022/08/29 02:44:57.353 +00:00] [INFO] [proxy/impl.go:3571] ["received get flush state request"] [request="segmentIDs:435615456365903873 segmentIDs:435615456365903874 "]
[2022/08/29 02:44:57.353 +00:00] [INFO] [datacoord/services.go:996] ["DataCoord receive get flush state request"] [segmentIDs="[435615456365903873,435615456365903874]"] [len=2]
[2022/08/29 02:44:57.353 +00:00] [INFO] [datacoord/services.go:1019] ["[flush state] unflushed segment ids"] [segmentIDs="[435615456365903873,435615456365903874]"] [len=2]
[2022/08/29 02:44:57.354 +00:00] [INFO] [proxy/impl.go:3585] ["received get flush state response"] [response="status:<> "]
[2022/08/29 02:44:57.856 +00:00] [INFO] [proxy/impl.go:3571] ["received get flush state request"] [request="segmentIDs:435615456365903873 segmentIDs:435615456365903874 "]
[2022/08/29 02:44:57.857 +00:00] [INFO] [datacoord/services.go:996] ["DataCoord receive get flush state request"] [segmentIDs="[435615456365903873,435615456365903874]"] [len=2]
[2022/08/29 02:44:57.857 +00:00] [INFO] [datacoord/services.go:1019] ["[flush state] unflushed segment ids"] [segmentIDs="[435615456365903873,435615456365903874]"] [len=2]
[2022/08/29 02:44:57.857 +00:00] [INFO] [proxy/impl.go:3585] ["received get flush state response"] [response="status:<> "]
[2022/08/29 02:44:58.360 +00:00] [INFO] [proxy/impl.go:3571] ["received get flush state request"] [request="segmentIDs:435615456365903873 segmentIDs:435615456365903874 "]
[2022/08/29 02:44:58.360 +00:00] [INFO] [datacoord/services.go:996] ["DataCoord receive get flush state request"] [segmentIDs="[435615456365903873,435615456365903874]"] [len=2]
[2022/08/29 02:44:58.361 +00:00] [INFO] [datacoord/services.go:1019] ["[flush state] unflushed segment ids"] [segmentIDs="[435615456365903873,435615456365903874]"] [len=2]
[2022/08/29 02:44:58.361 +00:00] [INFO] [proxy/impl.go:3585] ["received get flush state response"] [response="status:<> "]
[2022/08/29 02:44:58.863 +00:00] [INFO] [proxy/impl.go:3571] ["received get flush state request"] [request="segmentIDs:435615456365903873 segmentIDs:435615456365903874 "]
[2022/08/29 02:44:58.864 +00:00] [INFO] [datacoord/services.go:996] ["DataCoord receive get flush state request"] [segmentIDs="[435615456365903873,435615456365903874]"] [len=2]
[2022/08/29 02:44:58.864 +00:00] [INFO] [datacoord/services.go:1019] ["[flush state] unflushed segment ids"] [segmentIDs="[435615456365903873,435615456365903874]"] [len=2]
[2022/08/29 02:44:58.865 +00:00] [INFO] [proxy/impl.go:3585] ["received get flush state response"] [response="status:<> "]
[2022/08/29 02:44:58.960 +00:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:402] ["insertBufferNode flushBufferData failed, err = All attempts results:\nattempt #1:can't add empty string into payload\nattempt #2:can't add empty string into payload\nattempt #3:can't add empty string into payload\nattempt #4:can't add empty string into payload\nattempt #5:can't add empty string into payload\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:402\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102"]
[2022/08/29 02:44:58.960 +00:00] [ERROR] [datanode/flow_graph_insert_buffer_node.go:402] ["insertBufferNode flushBufferData failed, err = All attempts results:\nattempt #1:can't add empty string into payload\nattempt #2:can't add empty string into payload\nattempt #3:can't add empty string into payload\nattempt #4:can't add empty string into payload\nattempt #5:can't add empty string into payload\n"] [stack="github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate\n\t/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:402\ngithub.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work\n\t/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102"]
panic: insertBufferNode flushBufferData failed, err = All attempts results:
attempt #1:can't add empty string into payload
attempt #2:can't add empty string into payload
attempt #3:can't add empty string into payload
attempt #4:can't add empty string into payload
attempt #5:can't add empty string into payload


goroutine 2329 [running]:
github.com/milvus-io/milvus/internal/datanode.(*insertBufferNode).Operate(0xc00247c4b0, 0xc003648a50, 0x1, 0x1, 0x434ba80, 0xc00365e580, 0x0)
	/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_insert_buffer_node.go:403 +0x40f5
github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).work(0xc000e4a380)
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:102 +0x23b
created by github.com/milvus-io/milvus/internal/util/flowgraph.(*nodeCtx).Start
	/go/src/github.com/milvus-io/milvus/internal/util/flowgraph/node.go:70 +0x70

```

### Expected Behavior
Milvus can accept empty string.

_No response_

### Steps To Reproduce

1. download v2.1.1
wget https://github.com/milvus-io/milvus/releases/download/v2.1.1/milvus-standalone-docker-compose.yml -O docker-compose.yml

2. start a standalone server
docker-compose up -d

3. use this script to test
```markdown
import random
from pymilvus import (
    connections,
    FieldSchema, CollectionSchema, DataType,
    Collection,
    utility
)

if __name__ == '__main__':
    connections.connect(host=_HOST, port=_PORT)

    dim = 128
    field1 = FieldSchema(name="id", dtype=DataType.INT64, description="int64", is_primary=True)
    field2 = FieldSchema(name="vec", dtype=DataType.FLOAT_VECTOR, description="float vector", dim=dim)
    field3 = FieldSchema(name="str", dtype=DataType.VARCHAR, description="string",
                         max_length=128, is_primary=False)
    schema = CollectionSchema(fields=[field1, field2, field3], description="collection description")
    collection = Collection(name="TEST", data=None, schema=schema)

    num = 1000
    data = [
        [i for i in range(num)],  # id field
        [[random.random() for _ in range(dim)] for _ in range(num)],  # vector field
        ["" for _ in range(num)],  # string field
    ]
    print("Start insert ...")
    collection.insert(data)
    print("Insert finished")

    print("Row count:", collection.num_entities)
```

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yhmo**
#18872

Temp solution: not allow inserting empty string

Signed-off-by: yhmo <yihua.mo@zilliz.com>

### CODE REVIEW

File: internal/proxy/task_insert_test.go [hunk 1]
```diff
@@ -346,3 +347,70 @@ func TestInsertTask_CheckAligned(t *testing.T) {
...
+					},
+				},
+			},
+		},
+	}
+
+	err := it.checkVarcharFieldData()
+	assert.Nil(t, err)
+
+	values = append(values, "")
```
Comment (congqixia) [inline internal/proxy/task_insert_test.go:412]: `values` will be changed after resizing it while `it.FieldsData[1].Field...Data` still points to original `values` address.

**Review by congqixia — APPROVED** [review]
/lgtm
