### PR TITLE
fix describe rg api

### LINKED ISSUE #21962: [Bug]: [ResourceGroup] it hangs when describe a non exisitng resource grou
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230202-d41cc0b2
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): 2.3.0.dev29
```

### Current Behavior

client hang

### Expected Behavior

return error with msg in a second

### Steps To Reproduce

```markdown
utility.describe_resource_group('non_existing_rg_name')
```

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by weiliu1031**
Signed-off-by: Wei Liu <wei.liu@zilliz.com>
fix: #21962 #21971

### CODE REVIEW

File: internal/proxy/task.go [hunk 1]
```diff
@@ -2119,21 +2119,28 @@ func (t *DescribeResourceGroupTask) Execute(ctx context.Context) error {
...
-		Status: resp.Status,
-		ResourceGroup: &milvuspb.ResourceGroup{
-			Name:             rgInfo.GetName(),
-			Capacity:         rgInfo.GetCapacity(),
-			NumAvailableNode: rgInfo.NumAvailableNode,
-			NumLoadedReplica: loadReplicas,
-			NumOutgoingNode:  outgoingNodes,
-			NumIncomingNode:  incomingNodes,
-		},
+	if rgInfo != nil {
```
Comment (congqixia) [inline internal/proxy/task.go:2122]: Check response state code and error first before using response info

File: internal/proxy/task.go [hunk 2]
```diff
@@ -2108,7 +2108,6 @@ func (t *DescribeResourceGroupTask) Execute(ctx context.Context) error {
 	resp, err := t.queryCoord.DescribeResourceGroup(ctx, &querypb.DescribeResourceGroupRequest{
```
Comment (congqixia) [inline internal/proxy/task.go:2108]: This error is still not checked

**Review by congqixia — APPROVED** [review]
/lgtm
