### PR TITLE
Fix datanode panic due to concurrent compaction and delete processing

### LINKED ISSUE #27145: [Bug]: Standalone restarted once during test
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0-20230915-a42bc90c
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

some tests failed due to the standalone pod restarted

### Expected Behavior

image

### Steps To Reproduce

_No response_

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/deploy_test_for_release_cron/detail/deploy_test_for_release_cron/909/pipeline

log:

[artifacts-rocksmq-standalone-reinstall-909-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/12620522/artifacts-rocksmq-standalone-reinstall-909-pytest-logs.tar.gz)
[artifacts-rocksmq-standalone-reinstall-909-server-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/12620523/artifacts-rocksmq-standalone-reinstall-909-server-logs.1.tar.gz)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bigsheeper**
fix https://github.com/milvus-io/milvus/issues/27145

the datanode processing delete while compaction happened so flush can not succeed.
For fixing:

1. bring back blockall, ,make sure compaction sync segments and delete processing are mutexed.
2. change ttNode handle updateCheckPoint async, make sure all the flowgraph node is processed fast.
3. change some error handling

see also: https://github.com/milvus-io/milvus/pull/27158

### CODE REVIEW

File: internal/datanode/flow_graph_time_tick_node.go [hunk 1]
```diff
@@ -48,8 +50,17 @@ type ttNode struct {
 	BaseNode
 	vChannelName   string
 	channel        Channel
-	lastUpdateTime time.Time
+	lastUpdateTime *atomic.Time
 	dataCoord      types.DataCoord
+
+	updateCPLock  sync.Mutex
+	notifyChannel chan checkPoint
+	closeChannel  chan bool
```
Comment (XuanYang-cn) [inline internal/datanode/flow_graph_time_tick_node.go:58]: Please change it to `chan struct{}` for closeChannel

File: internal/datanode/channel_meta.go [hunk 2]
```diff
@@ -678,7 +678,7 @@ func (c *ChannelMeta) getCollectionSchema(collID UniqueID, ts Timestamp) (*schem
 	return c.collSchema, nil
 }
 
-func (c *ChannelMeta) mergeFlushedSegments(ctx context.Context, seg *Segment, planID UniqueID, compactedFrom []UniqueID) error {
+func (c *ChannelMeta) mergeFlushedSegments(ctx context.Context, seg *Segment, planID UniqueID, compactedFrom []UniqueID) {
```
Comment (XuanYang-cn) [inline internal/datanode/channel_meta.go:681]: ctx can be safely removed here since we don't check it anymore

File: internal/datanode/flow_graph_insert_buffer_node.go [hunk 3]
```diff
@@ -485,6 +486,9 @@ func (ibNode *insertBufferNode) Sync(fgMsg *flowGraphMsg, seg2Upload []UniqueID,
 				task.dropped,
 				endPosition)
 			if err != nil {
+				if errors.Is(err, merr.ErrSegmentNotFound) {
```
Comment (XuanYang-cn) [inline internal/datanode/flow_graph_insert_buffer_node.go:489]: Please user merr instead of errors

File: internal/datanode/flow_graph_insert_buffer_node.go [hunk 4]
```diff
@@ -497,13 +501,23 @@ func (ibNode *insertBufferNode) Sync(fgMsg *flowGraphMsg, seg2Upload []UniqueID,
 				metrics.DataNodeAutoFlushBufferCount.WithLabelValues(fmt.Sprint(paramtable.GetNodeID()), metrics.TotalLabel).Inc()
 			}
 
+			if errors.Is(err, merr.ErrSegmentNotFound) {
```
Comment (XuanYang-cn) [inline internal/datanode/flow_graph_insert_buffer_node.go:504]: Please user merr instead of errors

**Review by XuanYang-cn — CHANGES_REQUESTED** [review]

File: internal/datanode/flow_graph_time_tick_node.go [hunk 5]
```diff
@@ -72,43 +83,44 @@ func (ttn *ttNode) IsValidInMsg(in []Msg) bool {
...
-	if curTs.Sub(ttn.lastUpdateTime) >= updateChanCPInterval {
-		if err := ttn.updateChannelCP(channelPos); err == nil {
-			ttn.lastUpdateTime = curTs
-			log.Info("update channel cp periodically")
-			return []Msg{}
+	if curTs.Sub(ttn.lastUpdateTime.Load()) >= updateChanCPInterval {
+		select {
+		case ttn.notifyChannel <- checkPoint{curTs, channelPos}:
+		default:
 		}
```
Comment (XuanYang-cn) [inline internal/datanode/flow_graph_time_tick_node.go:105]: Please don't repeat yourself, make a func of it.

**Review by XuanYang-cn — CHANGES_REQUESTED** [review]

File: internal/util/flowgraph/node.go [hunk 6]
```diff
@@ -31,6 +31,8 @@ const (
 	// TODO: better to be configured
 	nodeCtxTtInterval = 2 * time.Minute
 	enableTtChecker   = true
+	// blockAll should wait no more than 10 seconds
+	blockAllWait = 10 * 1000
```
Comment (XuanYang-cn) [inline internal/util/flowgraph/node.go:35]: use time.duration please

**Review by XuanYang-cn — CHANGES_REQUESTED** [review]

File: internal/datanode/channel_meta.go (hunk 2 above)
Comment (bigsheeper) [reply internal/datanode/channel_meta.go:681]: ctx can be used for tracing

File: internal/datanode/flow_graph_insert_buffer_node.go (hunk 3 above)
Comment (bigsheeper) [reply internal/datanode/flow_graph_insert_buffer_node.go:489]: I don't get it

File: internal/datanode/flow_graph_time_tick_node.go (hunk 1 above)
Comment (bigsheeper) [reply internal/datanode/flow_graph_time_tick_node.go]: updated

File: internal/datanode/flow_graph_time_tick_node.go (hunk 5 above)
Comment (bigsheeper) [reply internal/datanode/flow_graph_time_tick_node.go:105]: updated

File: internal/util/flowgraph/node.go (hunk 6 above)
Comment (bigsheeper) [reply internal/util/flowgraph/node.go]: updated

**Comment by XuanYang-cn** [comment]
LGTM
