### PR TITLE
#1529 fix server crash when cache_insert_data enabled

### LINKED ISSUE #1529: Server crash when cache_insert_data enabled
**Describe the bug**
Test continued for an hour and then server crashed
log path: /test/milvus/db_data_070/sift_10m_1024_128_l2_sq8_wal_stability/logs
global.log
```
2020-03-06 00:38:09,569 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:10,700 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:11,873 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:13,003 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:14,179 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:14,788 | INFO | default | [SERVER] Server received critical signal: 11
2020-03-06 00:38:14,788 | INFO | default | [SERVER] Call stack:
2020-03-06 00:38:14,789 | INFO | default | [SERVER] ../bin/milvus_server(+0x286c20) [0x5586a2d82c20]
2020-03-06 00:38:14,789 | INFO | default | [SERVER] ../bin/milvus_server(+0x2871d1) [0x5586a2d831d1]
2020-03-06 00:38:14,789 | INFO | default | [SERVER] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fa11f56df20]
2020-03-06 00:38:14,789 | INFO | default | [SERVER] ../bin/milvus_server(+0x2cb32c) [0x5586a2dc732c]
2020-03-06 00:38:14,789 | INFO | default | [SERVER] ../bin/milvus_server(+0x2d1912) [0x5586a2dcd912]
2020-03-06 00:38:14,789 | INFO | default | [SERVER] ../bin/milvus_server(+0x147123) [0x5586a2c43123]
2020-03-06 00:38:14,789 | INFO | default | [SERVER] ../bin/milvus_server(+0x1395fa) [0x5586a2c355fa]
2020-03-06 00:38:14,789 | INFO | default | [SERVER] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd66f) [0x7fa11ff9366f]
2020-03-06 00:38:14,789 | INFO | default | [SERVER] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fa1202666db]
2020-03-06 00:38:14,789 | INFO | default | [SERVER] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fa11f65088f]
2020-03-06 00:38:15,313 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:16,461 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:17,599 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:18,769 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:19,902 | INFO | default | [WAL] record type 5 table  lsn 408025046961
2020-03-06 00:38:21,061 | INFO | default | [WAL] record type 5 table  lsn 408025046961
```
the last lines in debug.log:
```
2020-03-06 00:38:14,742 | DEBUG | default | [SERVER] DoSearch file id:212: totally cost (0.008989 second [8.989262 ms])
2020-03-06 00:38:14,742 | DEBUG | default | [SERVER] PickToExecute  (0.000001 second [0.000694 ms])
2020-03-06 00:38:14,742 | DEBUG | default | [ENGINE] Search Params: [k] 16 [nprobe] 41
2020-03-06 00:38:14,742 | DEBUG | default | [SERVER] PickToLoad  (0.000001 second [0.000703 ms])
2020-03-06 00:38:14,742 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: search prepare (0.000008 second [0.008048 ms])
2020-03-06 00:38:14,748 | DEBUG | default | [KNOWHERE] IVF search cost: 5581.88, quantization cost: 3.15405, data search cost: 2.42603
2020-03-06 00:38:14,748 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: search done (0.005667 second [5.667459 ms])
2020-03-06 00:38:14,748 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: map uids 1312 (0.000028 second [0.028180 ms])
2020-03-06 00:38:14,748 | DEBUG | default | [SERVER] DoSearch file id:213: job 92 nq 82 topk 16, do search (0.005721 second [5.721167 ms])
2020-03-06 00:38:14,748 | DEBUG | default | [SERVER] DoSearch file id:213: job 92 nq 82 topk 16, reduce topk (0.000026 second [0.025686 ms])
2020-03-06 00:38:14,748 | DEBUG | default | [SERVER] SearchJob 92 finish index file: 213
2020-03-06 00:38:14,748 | DEBUG | default | [SERVER] DoSearch file id:213: totally cost (0.005762 second [5.762442 ms])
2020-03-06 00:38:14,748 | DEBUG | default | [SERVER] PickToExecute  (0.000001 second [0.000610 ms])
2020-03-06 00:38:14,748 | DEBUG | default | [ENGINE] Search Params: [k] 16 [nprobe] 41
2020-03-06 00:38:14,748 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: search prepare (0.000009 second [0.008608 ms])
2020-03-06 00:38:14,752 | DEBUG | default | [SERVER] Search task load file id:258 DISK2CPU file type:3 size:294120911 bytes from location: /test/milvus/db_data_070/sift_10m_1024_128_l2_sq8_wal_stability/db/tables/sift_10m_1024_128_l2/1583423221803737000/1583423237191457000 totally cost (0.009491 second [9.490813 ms])
2020-03-06 00:38:14,752 | DEBUG | default | [SERVER] PickToLoad  (0.000000 second [0.000284 ms])
2020-03-06 00:38:14,752 | DEBUG | default | [SERVER] PickToLoad  (0.000000 second [0.000130 ms])
2020-03-06 00:38:14,752 | DEBUG | default | [SERVER] PickToLoad  (0.000000 second [0.000138 ms])
2020-03-06 00:38:14,778 | DEBUG | default | [KNOWHERE] IVF search cost: 29388.3, quantization cost: 3.11719, data search cost: 26.2688
2020-03-06 00:38:14,778 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: search done (0.029435 second [29.434991 ms])
2020-03-06 00:38:14,778 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: map uids 1312 (0.000027 second [0.027357 ms])
2020-03-06 00:38:14,778 | DEBUG | default | [SERVER] DoSearch file id:44: job 92 nq 82 topk 16, do search (0.029489 second [29.488795 ms])
2020-03-06 00:38:14,778 | DEBUG | default | [SERVER] DoSearch file id:44: job 92 nq 82 topk 16, reduce topk (0.000020 second [0.019935 ms])
2020-03-06 00:38:14,778 | DEBUG | default | [SERVER] SearchJob 92 finish index file: 44
2020-03-06 00:38:14,778 | DEBUG | default | [SERVER] DoSearch file id:44: totally cost (0.029525 second [29.524563 ms])
2020-03-06 00:38:14,778 | DEBUG | default | [SERVER] PickToExecute  (0.000001 second [0.000564 ms])
2020-03-06 00:38:14,778 | DEBUG | default | [ENGINE] Search Params: [k] 16 [nprobe] 41
2020-03-06 00:38:14,778 | DEBUG | default | [SERVER] PickToLoad  (0.000000 second [0.000352 ms])
2020-03-06 00:38:14,778 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: search prepare (0.000008 second [0.008455 ms])
2020-03-06 00:38:14,783 | DEBUG | default | [KNOWHERE] IVF search cost: 5254.88, quantization cost: 2.9502, data search cost: 2.302
2020-03-06 00:38:14,783 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: search done (0.005338 second [5.338454 ms])
2020-03-06 00:38:14,783 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: map uids 1312 (0.000023 second [0.023195 ms])
2020-03-06 00:38:14,783 | DEBUG | default | [SERVER] DoSearch file id:214: job 92 nq 82 topk 16, do search (0.005393 second [5.392650 ms])
2020-03-06 00:38:14,783 | DEBUG | default | [SERVER] DoSearch file id:214: job 92 nq 82 topk 16, reduce topk (0.000019 second [0.019155 ms])
2020-03-06 00:38:14,783 | DEBUG | default | [SERVER] SearchJob 92 finish index file: 214
2020-03-06 00:38:14,783 | DEBUG | default | [SERVER] DoSearch file id:214: totally cost (0.005427 second [5.427380 ms])
2020-03-06 00:38:14,783 | DEBUG | default | [SERVER] PickToExecute  (0.000000 second [0.000391 ms])
2020-03-06 00:38:14,783 | DEBUG | default | [ENGINE] Search Params: [k] 16 [nprobe] 41
2020-03-06 00:38:14,783 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: search prepare (0.000008 second [0.007881 ms])
2020-03-06 00:38:14,783 | DEBUG | default | [SERVER] PickToLoad  (0.000000 second [0.000270 ms])
2020-03-06 00:38:14,788 | DEBUG | default | [KNOWHERE] IVF search cost: 4548.7, quantization cost: 2.92188, data search cost: 1.62305
2020-03-06 00:38:14,788 | DEBUG | default | [SERVER] ExecutionEngineImpl::Search float: search done (0.004620 second [4.619976 ms])
2020-03-06 00:38:23,344 | DEBUG | default | [SERVER] Erase /test/milvus/db_data_070/sift_10m_1024_128_l2_sq8_wal_stability/db/tables/sift_10m_1024_128_l2/1583423221803737000/1583423221803737000 size: 1075200000 bytes from cache, usage: 1747925466 bytes, capacity: 68719476736 bytes
```
**Steps/Code to reproduce behavior**
Do search , insert , build ivf_sq8 index background
```
            while time.time() < start_time + during_time * 60:
                i = i + 1
                for j in range(insert_interval):
                    top_k = random.randint(l_top_k, g_top_k)
                    nq = random.randint(l_nq, g_nq)
                    nprobe = random.randint(l_nprobe, g_nprobe)
                    query_vectors = [[random.random() for _ in range(dimension)] for _ in range(nq)]
                    logger.debug("Query nprobe:%d, nq:%d, top-k:%d" % (nprobe, nq, top_k))
                    result = milvus_instance.query(query_vectors, top_k, nprobe)
                insert_vectors = [[random.random() for _ in range(dimension)] for _ in range(insert_xb)]
                status, res = milvus_instance.insert(insert_vectors, ids=[x for x in range(len(insert_vectors))])
                logger.debug("%d, row_count: %d" % (i, milvus_instance.count()))
```

**Expected behavior**

**Environment details**
```
2020-03-05 23:40:58,869 | INFO | default | [SERVER] Milvus Release version: v0.7.0, built at 2020-03-05 08:32.09
2020-03-05 23:40:58,869 | INFO | default | [SERVER] CPU edition
```
**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by cydrain**
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

**What type of PR is this?**
 bug 

**What this PR does / why we need it:**
server crash when cache_insert_data enabled

**Which issue(s) this PR fixes:**
Fixes #1529

**Special notes for your reviewer:**

**Does this PR introduce a user-facing change?:**

**Additional documentation (e.g. design docs, usage docs, etc.):**

### CODE REVIEW

**Review by youny626 — APPROVED** [review]

File: core/src/db/engine/ExecutionEngineImpl.cpp [hunk 1]
```diff
@@ -738,8 +740,14 @@ ExecutionEngineImpl::BuildIndex(const std::string& location, EngineType engine_t
 
     if (from_index) {
         status = to_index->BuildAll(Count(), from_index->GetRawVectors(), from_index->GetRawIds(), conf);
+        std::vector<segment::doc_id_t> uids = from_index->GetUids();
+        to_index->SetUids(uids);
+        ENGINE_LOG_DEBUG << "set uids " << to_index->GetUids().size() << " for " << location;
```
Comment (yhmo) [inline core/src/db/engine/ExecutionEngineImpl.cpp]: suggest tot combine two code sections into one

**Review by yhmo — APPROVED** [review]
