### PR TITLE
fix: [StorageV2] end to end minor issues for sync, stats, and load

### LINKED ISSUE #42862: [Enhancement]: [StorageV2] field id as column group id for wide column
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What would you like to be added?

At present, column group IDs are assigned as the index positions of written paths.
For column groups containing only a single wide column, we can assign the column group ID directly as the field ID.
This enables Milvus to determine whether a field is a wide column or part of a narrow column group without the need to read the file footer, improving read-time efficiency.
Note: this approach assumes that only one narrow column group exists for now.

### Why is this needed?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shaoting-huang**
Fix issues in end-to-end tests: 
1. **Split column groups based on schema**, rather than estimating by average chunk row size. **Ensure column group consistency within a segment**, to avoid errors caused by loading multiple column group chunks simultaneously.
2. **Use sorted segmentId** when generating the stats binlog path, to ensure consistent and correct file path resolution.
3. **Determine field IDs as follows**:
    For multi-column column groups, retrieve the field ID list from metadata.
    For single-column column groups, use the column group ID directly as the field ID.

related: #39173 
fix: #42862

### CODE REVIEW

File: internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp [hunk 1]
```diff
@@ -261,26 +261,29 @@ ChunkedSegmentSealedImpl::load_column_group_data_internal(
...
             row_group_meta_list.push_back(
                 reader->file_metadata()->GetRowGroupMetadataVector());
-        }
-
-        std::vector<FieldId> milvus_field_ids;
-        if (column_group_id == FieldId(DEFAULT_SHORT_COLUMN_GROUP_ID)) {
-            milvus_field_ids = narrow_column_field_ids_;
-        } else {
-            milvus_field_ids.push_back(column_group_id);
+            auto status = reader->Close();
```
Comment (tedxu) [inline internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp:273]: The reader opened twice: one for getting field list and the other for getting meta.

File: internal/datanode/index/task_stats.go [hunk 2]
```diff
@@ -430,6 +430,9 @@ func (st *statsTask) createTextIndex(ctx context.Context,
 	})
 
 	getInsertFiles := func(fieldID int64) ([]string, error) {
+		if st.req.GetStorageVersion() == storage.StorageV2 {
+			return []string{}, nil
```
Comment (tedxu) [inline internal/datanode/index/task_stats.go:434]: What does it mean by returning an empty slice?

**Review by tedxu — COMMENTED** [review]
/lgtm
