### PR TITLE
fix: skip dim check for non-vector fields in PreCheck (#41287)

### LINKED ISSUE #41287: [Bug]: PreCheck() in DataCoord triggers "failed to get dim from field type params" warning for non-vector fields
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.5.9
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-java
- OS(Ubuntu or CentOS): Ubuntu 22.04
- CPU/Memory: 64 cores / 40 Gi
- GPU: x
- Others:
```

### Current Behavior

When building indexes on **non-vector fields** (e.g., `VarChar`, `Bool`, `Float`, `Array`), Milvus emits repeated warnings like:

```
failed to get dim from field type params
field type: VarChar
error: dim not found in params
```

This happens even though these field types are not expected to have a `dim` parameter. The warning originates from `DataCoord` during `indexBuildTask.PreCheck()`.

### Expected Behavior

Milvus should **not attempt to fetch `dim`** from non-vector fields. The `PreCheck` step should first validate the field type and only call `GetDimFromParams()` for `FLOAT_VECTOR` or `BINARY_VECTOR` fields.

Warnings should not be emitted for valid schemas that apply inverted/bitmap indexes to non-vector fields.

### Steps To Reproduce

```markdown
1. Define a schema like below:

addField("title", DataType.VarChar, maxLength = 800)
addField("tagIds", DataType.Array, elementType = Int16)
addField("isValidEmbeddingProduct", DataType.Bool)

2. Create inverted/bitmap indexes:

createIndex("title", IndexType.INVERTED)
createIndex("tagIds", IndexType.INVERTED)
createIndex("isValidEmbeddingProduct", IndexType.BITMAP)

3. Observe Milvus logs during index build.
```

### Milvus Log

```
{"level":"WARN","time":"2025/04/14 13:48:50.701 +00:00","caller":"datacoord/task_index.go:210","message":"failed to get dim from field type params","field type":"VarChar","error":"dim not found in params","errorVerbose":"dim not found in params\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/storage.GetDimFromParams\n  | \t/workspace/source/internal/storage/utils.go:233\n  | github.com/milvus-io/milvus/internal/datacoord.(*indexBuildTask).PreCheck\n  | \t/workspace/source/internal/datacoord/task_index.go:208\n  | github.com/milvus-io/milvus/internal/datacoord.(*taskScheduler).processInit\n  | \t/workspace/source/internal/datacoord/task_scheduler.go:510\n  | github.com/milvus-io/milvus/internal/datacoord.(*taskScheduler).process\n  | \t/workspace/source/internal/datacoord/task_scheduler.go:418\n  | github.com/milvus-io/milvus/internal/datacoord.(*taskScheduler).run.func1\n  | \t/workspace/source/internal/datacoord/task_scheduler.go:390\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.7.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) dim not found in params\nError types: (1) *withstack.withStack (2) *errutil.leafError"}
```

### Anything else?

This issue leads to excessive noise in production logs and may confuse operators, even though it doesn’t affect functionality.

Suggestion:
- Skip `GetDimFromParams()` for non-vector fields during `PreCheck`
- Or downgrade the warning to debug

### PR DESCRIPTION
**Pull request by Hoyaspark**
## What this PR does

This PR fixes an issue where the `PreCheck` function in DataCoord logs unnecessary warnings 
when attempting to retrieve 'dim' from non-vector fields.

The change adds a check to only call `GetDimFromParams` when the field type is a vector type.

## Related issue

Fixes #41287

### CODE REVIEW

File: internal/datacoord/task_index.go [hunk 1]
```diff
@@ -207,11 +207,15 @@ func (it *indexBuildTask) PreCheck(ctx context.Context, dependency *taskSchedule
...
 	}
 
-	dim, err := storage.GetDimFromParams(field.GetTypeParams())
-	if err != nil {
-		log.Ctx(ctx).Warn("failed to get dim from field type params",
-			zap.String("field type", field.GetDataType().String()), zap.Error(err))
-		// don't return, maybe field is scalar field or sparseFloatVector
+	// Extract dim only for vector types to avoid unnecessary warnings
+	dim := -1
+	if typeutil.IsVectorType(field.GetDataType()) {
```
Comment (xiaocai2333) [inline internal/datacoord/task_index.go:212]: SparseFloatVector doesn't have a `dim` parameter either. It is recommended to use `typeutil.IsFixDimVectorType(field.GetDataType)`.

**Review by xiaocai2333 — COMMENTED** [review]
LGTM

**Comment by xiaocai2333** [comment]
/lgtm
@xiaofan-luan please approve on it.

@Hoyaspark Can you pick it to 2.5 branch?

**Comment by xiaocai2333** [comment]
I mean cherry-pick it into a new PR based on the 2.5 branch.

**Comment by Hoyaspark** [comment]
@xiaocai2333 I’ve created a new PR based on the 2.5 branch: [#41329](https://github.com/milvus-io/milvus/pull/41329)

**Review by czs007 — APPROVED** [review]
