### PR TITLE
fix: data race on rootcoord.proxyClientManager.proxyClient

### LINKED ISSUE #28786: [Bug]: data race on rootcoord.proxyClientManager.proxyClient
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:9c9ab08
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

in `CheckHealth` function, reading map does not have mutex protection

### Expected Behavior

No data race

### Steps To Reproduce

_No response_

### Milvus Log

```
2023-11-28T04:50:05.0857283Z ==================
2023-11-28T04:50:05.0857821Z WARNING: DATA RACE
2023-11-28T04:50:05.0867349Z Read at 0x00c00053cbd0 by goroutine 762:
2023-11-28T04:50:05.0869935Z   github.com/milvus-io/milvus/internal/rootcoord.(*Core).CheckHealth()
2023-11-28T04:50:05.0875527Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:2804 +0x287
2023-11-28T04:50:05.0881521Z   github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).CheckHealth()
2023-11-28T04:50:05.0883264Z       /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:93 +0xaa
2023-11-28T04:50:05.0884965Z   github.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_CheckHealth_Handler.func1()
2023-11-28T04:50:05.0886703Z       /go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:2347 +0x9e
2023-11-28T04:50:05.0888315Z   github.com/milvus-io/milvus/pkg/util/interceptor.ServerIDValidationUnaryServerInterceptor.func1()
2023-11-28T04:50:05.0889923Z       /go/src/github.com/milvus-io/milvus/pkg/util/interceptor/server_id_interceptor.go:54 +0x1ec
2023-11-28T04:50:05.0891520Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1()
2023-11-28T04:50:05.0893015Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x8e
2023-11-28T04:50:05.0894453Z   github.com/milvus-io/milvus/pkg/util/interceptor.ClusterValidationUnaryServerInterceptor.func1()
2023-11-28T04:50:05.0909919Z       /go/src/github.com/milvus-io/milvus/pkg/util/interceptor/cluster_interceptor.go:48 +0x255
2023-11-28T04:50:05.0911431Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1()
2023-11-28T04:50:05.0912299Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x8e
2023-11-28T04:50:05.0913113Z   github.com/milvus-io/milvus/pkg/util/logutil.UnaryTraceLoggerInterceptor()
2023-11-28T04:50:05.0913918Z       /go/src/github.com/milvus-io/milvus/pkg/util/logutil/grpc_interceptor.go:23 +0xa2
2023-11-28T04:50:05.0914964Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1()
2023-11-28T04:50:05.0915775Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x8e
2023-11-28T04:50:05.0916878Z   go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1()
2023-11-28T04:50:05.0918028Z       /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342 +0x6fa
2023-11-28T04:50:05.0919014Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1()
2023-11-28T04:50:05.0919856Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x8e
2023-11-28T04:50:05.0920603Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1()
2023-11-28T04:50:05.0921363Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0x126
2023-11-28T04:50:05.0922198Z   github.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_CheckHealth_Handler()
2023-11-28T04:50:05.0923099Z       /go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:2349 +0x26c
2023-11-28T04:50:05.0923760Z   google.golang.org/grpc.(*Server).processUnaryRPC()
2023-11-28T04:50:05.0924292Z       /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0x185e
2023-11-28T04:50:05.0924793Z   google.golang.org/grpc.(*Server).handleStream()
2023-11-28T04:50:05.0925292Z       /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0xff8
2023-11-28T04:50:05.0925872Z   google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-11-28T04:50:05.0926412Z       /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0xec
2023-11-28T04:50:05.0926753Z 
2023-11-28T04:50:05.0926918Z Previous write at 0x00c00053cbd0 by goroutine 338:
2023-11-28T04:50:05.0927302Z   runtime.mapassign_fast64()
2023-11-28T04:50:05.0927655Z       /usr/local/go/src/runtime/map_fast64.go:93 +0x0
2023-11-28T04:50:05.0928292Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).connect()
2023-11-28T04:50:05.0929126Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:119 +0x635
2023-11-28T04:50:05.0929986Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).AddProxyClient()
2023-11-28T04:50:05.0930858Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:87 +0x144
2023-11-28T04:50:05.0931723Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).AddProxyClient-fm()
2023-11-28T04:50:05.0932298Z       <autogenerated>:1 +0x44
2023-11-28T04:50:05.0932870Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).handlePutEvent()
2023-11-28T04:50:05.0933676Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:159 +0x2e9
2023-11-28T04:50:05.0934471Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).startWatchEtcd()
2023-11-28T04:50:05.0935249Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:140 +0x884
2023-11-28T04:50:05.0936049Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).WatchProxy.func1()
2023-11-28T04:50:05.0936854Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:104 +0x66
2023-11-28T04:50:05.0937445Z   golang.org/x/sync/errgroup.(*Group).Go.func1()
2023-11-28T04:50:05.0937954Z       /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x82
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Fix #28786

### CODE REVIEW

File: internal/rootcoord/root_coord.go [hunk 1]
```diff
@@ -2803,6 +2803,7 @@ func (c *Core) CheckHealth(ctx context.Context, in *milvuspb.CheckHealthRequest)
 	group, ctx := errgroup.WithContext(ctx)
 	errReasons := make([]string, 0, len(c.proxyClientManager.proxyClient))
 
+	c.proxyClientManager.lock.RLock()
 	for nodeID, proxyClient := range c.proxyClientManager.proxyClient {
```
Comment (yah01) [inline internal/rootcoord/root_coord.go:2807]: NIT: it would be better to make the field not visible, and get them by a method

**Review by yah01 — COMMENTED** [review]
/lgtm

File: internal/rootcoord/root_coord.go
Comment (PowderLi) [inline internal/rootcoord/root_coord.go:1]: please do RLock() before get the length of c.proxyClientManager.proxyClient

I met such data race:
```

2023-12-12T00:38:54.7600157Z ==================
2023-12-12T00:38:54.7601043Z WARNING: DATA RACE
2023-12-12T00:38:54.7604729Z Read at 0x00c000e558f0 by goroutine 761:
2023-12-12T00:38:54.7605782Z   github.com/milvus-io/milvus/internal/rootcoord.(*Core).CheckHealth()
2023-12-12T00:38:54.7607118Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/root_coord.go:2782 +0x287
2023-12-12T00:38:54.7609022Z   github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).CheckHealth()
2023-12-12T00:38:54.7610613Z       /go/src/github.com/milvus-io/milvus/internal/distributed/rootcoord/service.go:93 +0xaa
2023-12-12T00:38:54.7612309Z   github.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_CheckHealth_Handler.func1()
2023-12-12T00:38:54.7613958Z       /go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:2347 +0x9e
2023-12-12T00:38:54.7615736Z   github.com/milvus-io/milvus/pkg/util/interceptor.ServerIDValidationUnaryServerInterceptor.func1()
2023-12-12T00:38:54.7617753Z       /go/src/github.com/milvus-io/milvus/pkg/util/interceptor/server_id_interceptor.go:54 +0x1ec
2023-12-12T00:38:54.7619395Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1()
2023-12-12T00:38:54.7620898Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x8e
2023-12-12T00:38:54.7622604Z   github.com/milvus-io/milvus/pkg/util/interceptor.ClusterValidationUnaryServerInterceptor.func1()
2023-12-12T00:38:54.7624092Z       /go/src/github.com/milvus-io/milvus/pkg/util/interceptor/cluster_interceptor.go:48 +0x255
2023-12-12T00:38:54.7625052Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1()
2023-12-12T00:38:54.7626448Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x8e
2023-12-12T00:38:54.7628167Z   github.com/milvus-io/milvus/pkg/util/logutil.UnaryTraceLoggerInterceptor()
2023-12-12T00:38:54.7629681Z       /go/src/github.com/milvus-io/milvus/pkg/util/logutil/grpc_interceptor.go:23 +0xa2
2023-12-12T00:38:54.7630867Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1()
2023-12-12T00:38:54.7632095Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x8e
2023-12-12T00:38:54.7633674Z   go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1()
2023-12-12T00:38:54.7635613Z       /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.38.0/interceptor.go:342 +0x6fa
2023-12-12T00:38:54.7637397Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1()
2023-12-12T00:38:54.7638587Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x8e
2023-12-12T00:38:54.7639968Z   github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1()
2023-12-12T00:38:54.7641446Z       /go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0x126
2023-12-12T00:38:54.7643088Z   github.com/milvus-io/milvus/internal/proto/rootcoordpb._RootCoord_CheckHealth_Handler()
2023-12-12T00:38:54.7644521Z       /go/src/github.com/milvus-io/milvus/internal/proto/rootcoordpb/root_coord.pb.go:2349 +0x26c
2023-12-12T00:38:54.7645611Z   google.golang.org/grpc.(*Server).processUnaryRPC()
2023-12-12T00:38:54.7646479Z       /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0x185e
2023-12-12T00:38:54.7647195Z   google.golang.org/grpc.(*Server).handleStream()
2023-12-12T00:38:54.7647711Z       /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0xff8
2023-12-12T00:38:54.7648376Z   google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-12-12T00:38:54.7649270Z       /go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0xec
2023-12-12T00:38:54.7649880Z 
2023-12-12T00:38:54.7650162Z Previous write at 0x00c000e558f0 by goroutine 338:
2023-12-12T00:38:54.7650856Z   runtime.mapassign_fast64()
2023-12-12T00:38:54.7651222Z       /usr/local/go/src/runtime/map_fast64.go:93 +0x0
2023-12-12T00:38:54.7651906Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).connect()
2023-12-12T00:38:54.7652750Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:119 +0x635
2023-12-12T00:38:54.7653612Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).AddProxyClient()
2023-12-12T00:38:54.7654471Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_client_manager.go:87 +0x144
2023-12-12T00:38:54.7655544Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).AddProxyClient-fm()
2023-12-12T00:38:54.7656440Z       <autogenerated>:1 +0x44
2023-12-12T00:38:54.7657076Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).handlePutEvent()
2023-12-12T00:38:54.7657881Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:159 +0x2e9
2023-12-12T00:38:54.7658672Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).startWatchEtcd()
2023-12-12T00:38:54.7659462Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:140 +0x884
2023-12-12T00:38:54.7660266Z   github.com/milvus-io/milvus/internal/rootcoord.(*proxyManager).WatchProxy.func1()
2023-12-12T00:38:54.7661068Z       /go/src/github.com/milvus-io/milvus/internal/rootcoord/proxy_manager.go:104 +0x66
2023-12-12T00:38:54.7661652Z   golang.org/x/sync/errgroup.(*Group).Go.func1()
2023-12-12T00:38:54.7662162Z       /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x82
```
