### PR TITLE
Fix group checker ut

### LINKED ISSUE #21037: [Bug]: group checker ut failed occasionally
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

https://github.com/milvus-io/milvus/actions/runs/3635600945/jobs/6134843137

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by longjiquan**
/kind bug
fix: #21037 
Signed-off-by: longjiquan <jiquan.long@zilliz.com>

### CODE REVIEW

File: internal/util/timerecord/group_checker_test.go [hunk 1]
```diff
@@ -37,7 +38,10 @@ func TestGroupChecker(t *testing.T) {
 	})
 	gc2.Check("2")
 
-	assert.Equal(t, 500*time.Millisecond, gc2.d)
+	assert.Equal(t, duration, gc2.d)
+
+	// make sure that the check time of "1" and "2" are all out-of-date.
+	time.Sleep(duration)
```
Comment (yah01) [inline internal/util/timerecord/group_checker_test.go:44]: This wouldn't help, if "1" expired but "2" not, and the group checker started to check, it will write ["1"] into signal, and then later write ["1", "2"] after "2" also expired

Comment (yah01) [reply internal/util/timerecord/group_checker_test.go:44]: Just rebase the master, 500ms is long enough to catch both "1" and "2"

Comment (yah01) [reply internal/util/timerecord/group_checker_test.go:44]: Guess your base doesn't contain the 500ms (which was 10ms) modification

Comment (longjiquan) [reply internal/util/timerecord/group_checker_test.go:44]: Yeah, you are right that this patch won't help, thx for the explanation. So how about change the logic to wati unitl the signal received both "1" and "2"? By the way, I already tested the logic with the latest master branch, it seems that `500ms` didn't help too.

**Review by congqixia — APPROVED** [review]
/lgtm
