### PR TITLE
Release last version after expiration

### LINKED ISSUE #20134: [Bug]: ShardClusterVersion has memory leakage
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: e7df499
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

In shard cluster, CurrentVersion will always keep reference to last version, which cause segment status memory leakage.

### Expected Behavior

Last version shall be released after all reference is gone.

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

Related to #19731

### PR DESCRIPTION
**Pull request by congqixia**
Fix #20134 
Related to #19731 #19526 

/kind bug

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

### CODE REVIEW

File: internal/querynode/shard_cluster_version.go [hunk 1]
```diff
@@ -117,6 +117,8 @@ func (v *ShardClusterVersion) checkSafeGC() {
 				if v.lastVersion != nil {
 					<-v.lastVersion.Expire()
 				}
+				// release ther reference of last version, so it could be processed by gc
```
Comment (yah01) [inline internal/querynode/shard_cluster_version.go:120]: comment typo, `ther` -> `the`
