### PR TITLE
Abandon using protobuf to pass binaryset parameter

### LINKED ISSUE #15625: [Bug]: Failed to create Index when segment size is set to large than 2G
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:latest
- Deployment mode(standalone or cluster):all
- SDK version(e.g. pymilvus v2.0.0rc2):latest
- OS(Ubuntu or CentOS): Ubuntu
```

### Current Behavior

After the segment size was changed to 5GB during the test, an error was reported in the build index.
The reason for the error is that the hard size limit of Protobuf is 2GB, that is, if the index file exceeds 2GB, it cannot be transmitted in Protobuf format.

### Expected Behavior

should be able to build the index correctly.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by czs007**
fix: #15625 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

### CODE REVIEW

File: internal/core/src/indexbuilder/IndexWrapper.cpp [hunk 1]
```diff
@@ -164,7 +165,6 @@ IndexWrapper::BuildWithoutIds(const knowhere::DatasetPtr& dataset) {
         }
     }
     auto conf_adapter = knowhere::AdapterMgr::GetInstance().GetAdapter(index_type);
-    std::cout << "config_ when build index: " << config_ << std::endl;
```
Comment (DragonDriver) [inline internal/core/src/indexbuilder/IndexWrapper.cpp:167]: Better to keep this. Very useful to debug.
