### PR TITLE
Fix http server bug

### LINKED ISSUE #990: build_index_resources can be set to ['GPU0', 'GPU0', 'GPU0']
**Describe the bug**
build_index_resources can be set to ['GPU0', 'GPU0', 'GPU0'] 

**Steps/Code to reproduce behavior**
1, use rest API to set config/gpu_resources build_index_resources to ['GPU0', 'GPU0', 'GPU0']
2, API call returned code 200 and no error raised

**Expected behavior**
build_index_resources should be unique

**Environment details**

**Additional context**

### PR DESCRIPTION
**Pull request by BossZou**
**What type of PR is this?**
bug

**What this PR does / why we need it:**
Fix bugs.

**Which issue(s) this PR fixes:**
Fixes #990, #1075, #1082

### CODE REVIEW

**Review by XuPeng-SH — APPROVED** [review]

File: core/src/server/Config.cpp [hunk 1]
```diff
@@ -806,8 +818,18 @@ Config::CheckGpuResourceConfigBuildIndexResources(const std::vector<std::string>
...
+    std::unordered_set<std::string> value_set;
     for (auto& resource : value) {
         CONFIG_CHECK(CheckGpuResource(resource));
+        value_set.insert(resource);
+    }
+
+    if (value_set.size() != value.size()) {
+        std::string msg =
+            "Invalid gpu build index resource. "
+            "Possible reason: gpu_resource_config.build_index_resources contain repeated resources"
```
Comment (cydrain) [inline core/src/server/Config.cpp]: Possible reason: gpu_resource_config.build_index_resources contains duplicate resources

Comment (BossZou) [reply core/src/server/Config.cpp]: Done.

**Review by liangliu — APPROVED** [review]
