### PR TITLE
Fix coordinator fast restart

### LINKED ISSUE #28183: [Enhancement]: Improve recovery speed of standalone reboot
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Currently for standalone node, if restart happenes, coordinator has to wait until old session expire.

In this pr, we will improve it by:
1. Change default etcd ttl to 30s instead of 60s.
2. Try to purge old session if the old node has same address of current 

### Why is this needed?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xiaofan-luan**
fix #28183

### CODE REVIEW

File: internal/util/sessionutil/session_util.go [hunk 1]
```diff
@@ -467,6 +468,35 @@ func (s *Session) registerService() (<-chan *clientv3.LeaseKeepAliveResponse, er
...
+	}
+	for _, kv := range resp.Kvs {
+		session := &Session{}
+		err = json.Unmarshal(kv.Value, session)
+		if err != nil {
+			log.Warn("failed to unmarshal old session from etcd, ignore", zap.Any("key", key), zap.Error(err))
+			return
+		}
+
+		if session.Address == s.Address {
```
Comment (jaime0815) [inline internal/util/sessionutil/session_util.go:488]: We'd better add an extra condition to check node id is not equal?
