### PR TITLE
Fix task merge doesn't work

### LINKED ISSUE #23404: [Bug]: Tasks are never merged
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Tasks are never merged

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yah01**
/kind bug
fix #23404

### CODE REVIEW

File: internal/querynodev2/tasks/scheduler.go [hunk 1]
```diff
@@ -62,6 +62,30 @@ func (s *Scheduler) Add(task Task) bool {
...
+				select {
+				case t = <-s.searchWaitQueue:
+					// Continue the loop to merge task
+				default:
+					break outer
+				}
+			}
+		}
+
 		if len(s.mergedSearchTasks) > 0 {
```
Comment (congqixia) [inline internal/querynodev2/tasks/scheduler.go:89]: Move process mergedSearchTasks here may cause some task never executed

**Review by congqixia — CHANGES_REQUESTED** [review]

**Review by congqixia — APPROVED** [review]
/lgtm
