### PR TITLE
Fix DML channel AsProducer after Close

### LINKED ISSUE #16351: [Bug]: TimeTickSync logic msgstream reuse logic is weird
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We have a refcnt of each msgstream, if refcnt == 0 then close the msgstream.

The problem is  closed stream should be no longer reused by AsProduder, which is really weird.

### Expected Behavior

don't close the stream but only wait for use.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xiaofan-luan**
fix #16351 
Signed-off-by: xiaofan-luan <xiaofan.luan@zilliz.com>

### CODE REVIEW

File: internal/rootcoord/dml_channels.go [hunk 1]
```diff
@@ -62,6 +62,7 @@ func newDmlChannels(ctx context.Context, factory msgstream.Factory, chanNamePref
 			log.Error("Failed to add msgstream", zap.String("name", name), zap.Error(err))
 			panic("Failed to add msgstream")
 		}
+		ms.AsProducer([]string{name})
```
Comment (cydrain) [inline internal/rootcoord/dml_channels.go:65]: We don't create producer here is intentional.
You can check #10050

File: internal/rootcoord/dml_channels.go [hunk 2]
```diff
@@ -159,9 +160,6 @@ func (d *dmlChannels) addChannels(names ...string) {
 		dms := v.(*dmlMsgStream)
 
 		dms.mutex.Lock()
-		if dms.refcnt == 0 {
```
Comment (cydrain) [inline internal/rootcoord/dml_channels.go:162]: please refer to #10093
