### PR TITLE
Fix timestamp go back issue

### LINKED ISSUE #6988: CI log error "timestamp go back"
#### Steps/Code to reproduce:
run milvus/tests/python_test

#### Expected result:
no ERROR in logs

#### Actual results:
find ERROR like:
```
[2021/08/04 11:46:34.683 +08:00] [DEBUG] [timeticksync.go:106] ["timestamp go back"] ["source id"=1] ["prev ts"=426783223219224593] ["curr ts"=426783223219224591]
```

### PR DESCRIPTION
**Pull request by cydrain**
Resolves: #6988 
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
please hold the issue, I thought the entire design is wrong, we need further discussion

File: internal/rootcoord/timeticksync.go [hunk 1]
```diff
@@ -26,11 +27,21 @@ import (
...
+}
+
 type timetickSync struct {
 	core          *Core
 	lock          sync.Mutex
 	proxyTimeTick map[typeutil.UniqueID]*channelTimeTickMsg
 	sendChan      chan map[typeutil.UniqueID]*channelTimeTickMsg
+
+	// record ddl timetick info
+	ddlLock  sync.RWMutex
```
Comment (xiaofan-luan) [inline internal/rootcoord/timeticksync.go:42]: RWMutex is this a reentrant lock? otherwise this may cause deadlock?

File: internal/rootcoord/timeticksync.go [hunk 2]
```diff
@@ -101,20 +169,45 @@ func (t *timetickSync) UpdateTimeTick(in *internalpb.ChannelTimeTickMsg) error {
 	if !ok {
 		return fmt.Errorf("Skip ChannelTimeTickMsg from un-recognized proxy node %d", in.Base.SourceID)
 	}
+
+	// if from ddl operation, remove ddl timetick firstly
+	if ddl {
+		t.RemoveDdlTimeTick(in.DefaultTimestamp, reason)
+	} else {
+		// if ddl operation with smaller ts is in process, skip current ts update
+		ddlMinTs := t.GetDdlMinTimeTick()
```
Comment (xiaofan-luan) [inline internal/rootcoord/timeticksync.go:178]: even if we remove current ddl, should we still check DdlMinTimeTick if we have multiple DDLs inqueue

File: internal/rootcoord/timeticksync.go [hunk 3]
```diff
@@ -101,20 +169,45 @@ func (t *timetickSync) UpdateTimeTick(in *internalpb.ChannelTimeTickMsg) error {
 	if !ok {
 		return fmt.Errorf("Skip ChannelTimeTickMsg from un-recognized proxy node %d", in.Base.SourceID)
 	}
+
+	// if from ddl operation, remove ddl timetick firstly
+	if ddl {
+		t.RemoveDdlTimeTick(in.DefaultTimestamp, reason)
```
Comment (xiaofan-luan) [inline internal/rootcoord/timeticksync.go:175]: t.RemoveDdlTimeTick is called to remove timestamp, I would suggest to call t.RemoveDdlTimeTick before t.core.SendTimeTick(ts, true, reason) and remote ddl parameter

File: internal/rootcoord/timeticksync.go [hunk 4]
```diff
@@ -84,10 +99,63 @@ func (t *timetickSync) sendToChannel() {
...
+	t.ddlLock.Lock()
+	defer t.ddlLock.Unlock()
+
+	return t.ddlMinTs
 }
 
 // UpdateTimeTick check msg validation and send it to local channel
-func (t *timetickSync) UpdateTimeTick(in *internalpb.ChannelTimeTickMsg) error {
+func (t *timetickSync) UpdateTimeTick(in *internalpb.ChannelTimeTickMsg, ddl bool, reason string) error {
 	t.lock.Lock()
```
Comment (xiaofan-luan) [inline internal/rootcoord/timeticksync.go:159]: ddllock and lock is causing deadlock here.

At startTimeTickLoop function we get ddl lock.
inside update time tick we get t.lock.
if removeDdlTimeTick is called it is another ddl lock.
That's the traditional ABA deadlock

File: internal/rootcoord/timeticksync.go (hunk 3 above)
Comment (xiaofan-luan) [reply internal/rootcoord/timeticksync.go:175]: sorry ,remove ddl parameter, this also help solve the deadlock

File: internal/rootcoord/timeticksync.go (hunk 4 above)
Comment (xiaofan-luan) [reply internal/rootcoord/timeticksync.go:159]: to solve the deadlock
1) make sure lock and ddl are acquired in specific order
or 
2) remove one of the lock by using atomic operation or by syncMap

File: internal/rootcoord/timeticksync.go (hunk 2 above)
Comment (cydrain) [reply internal/rootcoord/timeticksync.go:178]: updated

File: internal/rootcoord/timeticksync.go (hunk 3 above)
Comment (cydrain) [reply internal/rootcoord/timeticksync.go:175]: updated

File: internal/rootcoord/timeticksync.go (hunk 4 above)
Comment (cydrain) [reply internal/rootcoord/timeticksync.go:159]: I have move RemoveDdlTimetick outside of UpdateTimeTick, there will be no ABA deadlock.
