### PR TITLE
Fix proxy panicking when QueryCoord offline

### LINKED ISSUE #23253: [Bug]: proxy panic when calling `GetReplicas` while querycoord offline
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.5 & 2.2.3
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

proxy panic when calling `GetReplicas` while querycoord offline

### Expected Behavior

Proxy shall not proxy when any other component go offline temporary 

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Fix #23253 
/kind bug

### CODE REVIEW

File: internal/proxy/impl.go [hunk 1]
```diff
@@ -3531,18 +3531,18 @@ func (node *Proxy) GetReplicas(ctx context.Context, req *milvuspb.GetReplicasReq
...
 
-	resp, err := node.queryCoord.GetReplicas(ctx, req)
+	r, err := node.queryCoord.GetReplicas(ctx, req)
 	if err != nil {
-		log.Error("Failed to get replicas from Query Coordinator",
+		log.Warn("Failed to get replicas from Query Coordinator",
 			zap.Error(err))
-		resp.Status.ErrorCode = commonpb.ErrorCode_UnexpectedError
-		resp.Status.Reason = err.Error()
+		resp.Status = &commonpb.Status{
```
Comment (jiaoew1991) [inline internal/proxy/impl.go:3538]: use merr package to simplify it ?

Comment (congqixia) [reply internal/proxy/impl.go]: fixed
