### PR TITLE
fix: validate collection TTL property to prevent compaction stuck

### LINKED ISSUE #46716: [Bug]: malformed collection ttl property causing compaction stuck
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: master(c2677967ad)
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

If collection ttl property is not valid, all compactin will stuck

### Expected Behavior

Milvus shall validate all input ttl setting 

### Steps To Reproduce

```markdown

```

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
If collection TTL property is malformed (e.g., non-numeric value), compaction tasks would fail silently and get stuck. This change:

- Add centralized GetCollectionTTL/GetCollectionTTLFromMap functions in pkg/common to handle TTL parsing with proper error handling
- Validate TTL property in createCollectionTask and alterCollectionTask PreExecute to reject invalid values early
- Refactor datacoord compaction policies to use the new common functions
- Remove duplicated getCollectionTTL from datacoord/util.go

issue: #46716

- Core invariant: collection.ttl.seconds must be a parseable int64 and validated at collection creation/alter time so malformed TTLs never reach compaction/execution codepaths.
- Bug fix (resolves #46716): malformed/non-numeric TTLs could silently cause compaction tasks to fail/stall; fixed by adding centralized parsing helpers pkg/common.GetCollectionTTL and GetCollectionTTLFromMap and validating TTL in createCollectionTask.PreExecute and alterCollectionTask.PreExecute (calls with default -1 and return parameter-invalid errors on parse failure).
- Simplification / removed redundancy: eliminated duplicated getCollectionTTL in internal/datacoord/util.go and replaced ad-hoc TTL parsing across datacoord (compaction policies, import_util, compaction triggers) and proxy util with the common helpers, centralizing error handling and defaulting logic.
- No data loss or behavior regression: valid TTL parsing semantics unchanged (helpers use identical int64 parsing and default fallback from paramtable/CommonCfg); validation occurs in PreExecute so existing valid collections proceed unchanged while malformed values are rejected early—compaction codepaths now receive only validated TTL values (or explicit defaults), preventing silent skips without altering valid execution flows.

### CODE REVIEW

File: internal/proxy/util.go [hunk 1]
```diff
@@ -2673,22 +2673,19 @@ func GetBM25FunctionOutputFields(collSchema *schemapb.CollectionSchema) []string
...
+// or return global ttl if collection's ttl is not specified
+// this is a helper util wrapping common.GetCollectionTTL without returning error
 func getCollectionTTL(pairs []*commonpb.KeyValuePair) uint64 {
-	properties := make(map[string]string)
-	for _, pair := range pairs {
-		properties[pair.Key] = pair.Value
+	defaultTTL := paramtable.Get().CommonCfg.EntityExpirationTTL.GetAsDuration(time.Second)
+	ttl, err := common.GetCollectionTTL(pairs, defaultTTL)
+	if err != nil {
+		ttl = defaultTTL
```
Comment (liliu-z) [inline internal/proxy/util.go:2684]: shall we throw exception here?

Comment (congqixia) [reply internal/proxy/util.go:2684]: since we have malformed ttl property already, throw exception here may cause unexpected behavior on proxy.
I shall add an error log here.

**Review by liliu-z — APPROVED** [review]
/approve
/lgtm
