### PR TITLE
enhance: add detailed stack for error message

### LINKED ISSUE #40882: [Enhancement]: Add stack trace if search faield
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What would you like to be added?

[2025/03/23 13:02:36.889 +00:00] [WARN] [querynodev2/services.go:715] ["failed to search segments"] [traceID=a801ed69bc5f290727fb90e9b55f5b21] [msgID=0] [collectionID=456702011469928512] [channel=1bf4e0d2-81be-4f2a-b415-86740012c207-topic-2_456702011469928512v0] [scope=Historical] [error="Operator::GetOutput failed for [Operator:, plan node id: 12843] : map::at"]

it's very heard to understand which line of the code is is, we should add error stack here.

### Why is this needed?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xiaofan-luan**
fix #40882
adding stacktrace will operator execute failed.

### CODE REVIEW

File: internal/core/src/exec/Driver.cpp [hunk 1]
```diff
@@ -182,23 +180,29 @@ Driver::Next(std::shared_ptr<BlockingState>& blocking_state) {
     try {                                                                      \
         call_func;                                                             \
     } catch (SegcoreError & e) {                                               \
```
Comment (zhengbuqian) [inline internal/core/src/exec/Driver.cpp:182]: this `catch (SegcoreError & e)` branch is now identical to the `catch (std::exception & e)` branch after added `LOG_ERROR(err_msg);` to the later, this branch can be removed.
