### PR TITLE
Fix #3515: error should be raised if tag name as params of `has_partition` is set invalid

### LINKED ISSUE #3515: Error should be raised if tag name as params of `has_partition` is set invalid
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
```
test_partition.py::TestHasBase::test_has_partition_with_invalid_tag_name[None] PASSED                                                                                               [ 23%]
test_partition.py::TestHasBase::test_has_partition_with_invalid_tag_name[12-s] FAILED                                                                                               [ 23%]
test_partition.py::TestHasBase::test_has_partition_with_invalid_tag_name[ ] FAILED                                                                                                  [ 23%]
test_partition.py::TestHasBase::test_has_partition_with_invalid_tag_name[12 s] FAILED                                                                                               [ 24%]
test_partition.py::TestHasBase::test_has_partition_with_invalid_tag_name[ siede ] FAILED                                                                                            [ 24%]
test_partition.py::TestHasBase::test_has_partition_with_invalid_tag_name[(mn)] FAILED                                                                                               [ 24%]
test_partition.py::TestHasBase::test_has_partition_with_invalid_tag_name[\u4e2d\u6587] FAILED                                                                                       [ 24%]
test_partition.py::TestHasBase::test_has_partition_with_invalid_tag_name[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] FAILED [ 24%]

```

**Steps/Code to reproduce behavior**

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by cqy123456**
**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which branch you want to cherry-pick to?**

Not Available

**Which issue(s) this PR fixes:**

Fixes #3515

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

File: core/src/server/ValidationUtil.cpp [hunk 1]
```diff
@@ -116,7 +116,7 @@ ValidateCollectionName(const std::string& collection_name) {
     int64_t table_name_size = collection_name.size();
     for (int64_t i = 1; i < table_name_size; ++i) {
         char name_char = collection_name[i];
-        if (name_char != '_' && std::isalnum(name_char) == 0) {
+        if (name_char != '_' && name_char != '$' && std::isalnum(name_char) == 0) {
```
Comment (cydrain) [inline core/src/server/ValidationUtil.cpp:119]: suggest to define a global unordered_set:
  const unordered_set<char> valid_collection_char_set = {'_', '$'};

Comment (shengjun1985) [reply core/src/server/ValidationUtil.cpp:119]: I don't think it is necessary to define 'valid_collection_char_set' since [0-9,a-z,A-Z] are all valid.
Furthermore, what is a valid name may be changed again and again……
