### PR TITLE
Use chunkManager rather than minio.Client in datanode garbage collection

### LINKED ISSUE #18023: [Bug]: Datanode garbage collection should use chunkmanager rather than use minio.Client directly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

If we want to use local disk on some scenarios, the garbage colleciton won't work.
Use minio client or etcd client destroy the encapsulation

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by EricStarer**
Use chunkManager rather than minio.Client in datanode garbage collection

Signed-off-by: xingzhao <xing.zhao@zilliz.com>

Fix https://github.com/milvus-io/milvus/issues/18023

### CODE REVIEW

**Comment by EricStarer** [comment]
rerun ut

**Comment by EricStarer** [comment]
rerun ut

**Comment by EricStarer** [comment]
rerun ut

**Comment by EricStarer** [comment]
rerun ut

**Comment by EricStarer** [comment]
rerun ut

File: internal/datacoord/server.go [hunk 1]
```diff
@@ -353,39 +354,50 @@ func (s *Server) stopCompactionTrigger() {
...
-		if err != nil {
-			return err
+		cli = &storage.MinioChunkManager{
+			Ctx:        s.ctx,
+			Client:     minioCli,
+			BucketName: Params.MinioCfg.BucketName,
 		}
+		log.Info("minio chunk manager init success.", zap.String("bucketname", Params.MinioCfg.BucketName))
+	} else if Params.CommonCfg.StorageType == "local" {
+		path := Params.LoadWithDefault("localStorage.Path", "/tmp/milvus/data")
```
Comment (soothing-rain) [inline internal/datacoord/server.go:393]: Maybe `params.LocalStorageCfg.Path` instead?

File: internal/datacoord/server.go [hunk 2]
```diff
@@ -353,39 +354,50 @@ func (s *Server) stopCompactionTrigger() {
...
-		// 3. datacoord try to create but failed with bucket already exists error
-		err = retry.Do(s.ctx, getCheckBucketFn(cli), retry.Attempts(2))
-		if err != nil {
-			return err
+		cli = &storage.MinioChunkManager{
+			Ctx:        s.ctx,
+			Client:     minioCli,
+			BucketName: Params.MinioCfg.BucketName,
 		}
+		log.Info("minio chunk manager init success.", zap.String("bucketname", Params.MinioCfg.BucketName))
```
Comment (soothing-rain) [inline internal/datacoord/server.go:391]: remove the ending `.` while printing logs

File: internal/datacoord/server.go [hunk 3]
```diff
@@ -353,39 +354,50 @@ func (s *Server) stopCompactionTrigger() {
...
+	} else if Params.CommonCfg.StorageType == "local" {
+		path := Params.LoadWithDefault("localStorage.Path", "/tmp/milvus/data")
+		cli = storage.NewLocalChunkManager(storage.RootPath(path))
```
Comment (soothing-rain) [inline internal/datacoord/server.go:394]: Add logs similar to minio case: local chunk manager init success

File: internal/storage/local_chunk_manager.go [hunk 4]
```diff
@@ -254,3 +257,20 @@ func (lcm *LocalChunkManager) RemoveWithPrefix(prefix string) error {
...
+
+func (lcm *LocalChunkManager) GetModTime(filename string) (time.Time, error) {
+	f, err := os.Open(filename)
+	if err != nil {
+		log.Error("open file error", zap.String("filename", filename))
+		return time.Now(), err
+	}
+	defer f.Close()
+
+	fi, err := f.Stat()
```
Comment (jiaoew1991) [inline internal/storage/local_chunk_manager.go:269]: use `os.Stat` is enough🤔

File: internal/datacoord/server.go (hunk 1 above)
Comment (EricStarer) [reply internal/datacoord/server.go:393]: ok

[the remark this answers is not in the document]
Comment (EricStarer) [reply internal/datacoord/server.go:393]: ok

File: internal/storage/local_chunk_manager.go (hunk 4 above)
Comment (EricStarer) [reply internal/storage/local_chunk_manager.go:269]: ok

File: internal/datacoord/server.go [hunk 5]
```diff
@@ -353,39 +354,50 @@ func (s *Server) stopCompactionTrigger() {
...
-		// TODO: We call minio.New in different places with same procedures to call several functions.
-		// We should abstract this to a focade function to avoid applying changes to only one place.
-		cli, err = minio.New(Params.MinioCfg.Address, &minio.Options{
-			Creds:  creds,
-			Secure: Params.MinioCfg.UseSSL,
-		})
-		if err != nil {
-			return fmt.Errorf("failed to create minio client: %v", err)
+	var cli storage.ChunkManager
+	if Params.CommonCfg.StorageType == "minio" {
```
[the remark this answers is not in the document]
Comment (EricStarer) [reply internal/datacoord/server.go:358]: Because there are some special process to initial minio client here, such as retry times of CheckBucketFn().

[the remark this answers is not in the document]
Comment (jiaoew1991) [reply internal/datacoord/server.go:358]: > Because there are some special process to initial minio client here, such as retry times of CheckBucketFn().

maybe extend `ChunkManagerFactory` is a better way

[the remark this answers is not in the document]
Comment (EricStarer) [reply internal/datacoord/server.go:358]: ok, after the discussion with yuchen, we use the chunkmanagerfactory

**Comment by EricStarer** [comment]
rerun ut

File: internal/storage/local_chunk_manager.go [hunk 6]
```diff
@@ -258,3 +261,14 @@ func (lcm *LocalChunkManager) RemoveWithPrefix(prefix string) error {
 	}
 	return lcm.MultiRemove(filePaths)
 }
+
+func (lcm *LocalChunkManager) GetModTime(filename string) (time.Time, error) {
+	absPath := path.Join(lcm.localPath, filename)
+	fi, err := os.Stat(absPath)
+	if err != nil {
+		log.Error("stat fileinfo error", zap.String("filename", filename))
+		return time.Now(), err
```
Comment (soothing-rain) [inline internal/storage/local_chunk_manager.go:270]: Returning `time.Now()` is confusing and error-prone, just return the default zero value.

File: internal/storage/minio_chunk_manager.go [hunk 7]
```diff
@@ -92,7 +93,7 @@ func newMinioChunkManagerWithConfig(ctx context.Context, c *config) (*MinioChunk
 		}
 		return nil
 	}
-	err = retry.Do(ctx, checkBucketFn, retry.Attempts(20))
+	err = retry.Do(ctx, checkBucketFn, retry.Attempts(2))
```
Comment (xige-16) [inline internal/storage/minio_chunk_manager.go:96]: Will reducing the number of retries cause stability problems?

Comment (EricStarer) [reply internal/storage/minio_chunk_manager.go:96]: screenshot-20220714-183533
here it explain why the retry time is 2, and I just follow this instruction

Comment (EricStarer) [reply internal/storage/minio_chunk_manager.go:96]: https://github.com/milvus-io/milvus/pull/18092/files#diff-8eecd044ceb67df3c20162d99ffe0dd511c5e932418942255d27a4b2034e6818L374-L378

File: internal/storage/minio_chunk_manager.go [hunk 8]
```diff
@@ -106,6 +107,12 @@ func newMinioChunkManagerWithConfig(ctx context.Context, c *config) (*MinioChunk
 	return mcm, nil
 }
 
+// SetVar set the variable value of mcm
+func (mcm *MinioChunkManager) SetVar(ctx context.Context, bucketName string) {
```
Comment (xige-16) [inline internal/storage/minio_chunk_manager.go:111]: The naming is weird, and the function doesn't seem necessary

File: internal/storage/minio_chunk_manager.go [hunk 9]
```diff
@@ -312,3 +319,19 @@ func (mcm *MinioChunkManager) ListWithPrefix(prefix string, recursive bool) ([]s
...
+	object, err := mcm.Client.GetObject(mcm.ctx, mcm.bucketName, filename, minio.GetObjectOptions{})
+	if err != nil {
+		log.Error("minio getObject error", zap.String("bucketName", mcm.bucketName), zap.String("filename", filename))
+		return time.Now(), err
+	}
+
+	objectInfo, err := object.Stat()
+	if err != nil {
+		log.Error("minio stat error", zap.String("bucketName", mcm.bucketName), zap.String("filename", filename))
+		return time.Now(), err
```
Comment (xige-16) [inline internal/storage/minio_chunk_manager.go:333]: you could just return time.Time{} (0001-01-01 00:00:00 +0000 UTC) instead of time.now(). and time.Time.IsZero(time.Time{}) == true

File: internal/storage/minio_chunk_manager.go (hunk 7 above)
Comment (xige-16) [reply internal/storage/minio_chunk_manager.go:96]: other components are also using miniochunkmanager, this configuration will also work for other components, I think this configuration can be changed in other pr.

File: internal/storage/minio_chunk_manager.go (hunk 9 above)
Comment (EricStarer) [reply internal/storage/minio_chunk_manager.go:333]: ok

File: internal/storage/local_chunk_manager.go (hunk 6 above)
Comment (EricStarer) [reply internal/storage/local_chunk_manager.go:270]: ok

File: internal/datacoord/garbage_collector.go [hunk 10]
```diff
@@ -197,10 +202,17 @@ func getLogs(sinfo *SegmentInfo) []*datapb.Binlog {
...
+		err := gc.option.cli.Remove(l.GetLogPath())
+		if err != nil {
+			switch err.(type) {
+			case minio.ErrorResponse:
+				errResp := minio.ToErrorResponse(err)
+				if errResp.Code != "" && errResp.Code != "NoSuchKey" {
+					delFlag = false
+				}
+			default:
+				delFlag = false
```
[the remark this answers is not in the document]
Comment (EricStarer) [reply internal/datacoord/garbage_collector.go:219]: when err is from minio, we should also check whether the file has been removed.

File: internal/storage/minio_chunk_manager.go (hunk 9 above)
Comment (EricStarer) [reply internal/storage/minio_chunk_manager.go]: ok

File: internal/storage/minio_chunk_manager.go (hunk 8 above)
Comment (EricStarer) [reply internal/storage/minio_chunk_manager.go:110]: it's just for a easier test.

File: internal/storage/minio_chunk_manager.go (hunk 7 above)
Comment (EricStarer) [reply internal/storage/minio_chunk_manager.go:95]: ok I will change back the retry times

File: internal/storage/local_chunk_manager.go (hunk 6 above)
Comment (EricStarer) [reply internal/storage/local_chunk_manager.go]: ok
