### PR TITLE
Fix timetick inconsistency in drop collection

### LINKED ISSUE #15406: [Bug]: DataNode goroutine leaks
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

DataNode goroutine 在跑完 CI 之后有泄露

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by XuanYang-cn**
When rootcoord drops a collection, it'll produce a `drop-collection DDL` msg
and one last timetick into DML channels of this collection.
So that when DataNode receives this msg, DN can release the resources for the specific collection.

Before this PR, RootCoord produced these two msgs with an older timestamp, generated
before many time-consuming RPCs.

Once these RPCs spend more time than timetick producing interval, the timetick of these 2 msgs are
older to the channel current timestamp, causing in-consistency in time, thus
making msgstream fail to consume the last `drop-collection DDL` msg.

This PR generates a new timestamp for `drop-collection DDL` msg and timetick msg after those time-consuming
RPCs

Fixes: #15406

/kind bug

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

### CODE REVIEW

File: internal/rootcoord/task.go [hunk 1]
```diff
@@ -324,6 +324,12 @@ func (t *DropCollectionReqTask) Execute(ctx context.Context) error {
 		t.core.ddlLock.Lock()
```
Comment (xiaofan-luan) [inline internal/rootcoord/task.go:324]: should we put the t.core.chanTimeTick.addDdlTimeTick(ts, reason) at the very begining of the task?

I thought the main reason is not because the time consuming task, but we don't handle timetick correctly.
