### PR TITLE
Fix DN GC bug

### LINKED ISSUE #12249: [Bug]: DN GC collection release unexpected flowgraph
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

/assign

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by XuanYang-cn**
Fixes: #12249

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

/kind bug

### CODE REVIEW

File: internal/datanode/compaction_executor.go [hunk 1]
```diff
@@ -98,12 +98,11 @@ func (c *compactionExecutor) stopTask(planID UniqueID) {
 	}
 }
 
-func (c *compactionExecutor) stopExecutingtaskByCollectionID(collID UniqueID) {
+func (c *compactionExecutor) stopExecutingtaskByVChannelName(vChannelName string) {
 	c.executing.Range(func(key interface{}, value interface{}) bool {
-		if value.(compactor).getCollection() == collID {
+		if value.(compactionTask).plan.GetChannel() == vChannelName {
```
Comment (congqixia) [inline internal/datanode/compaction_executor.go:103]: map value should be compactor or *compactionTask, this assertion will panic

**Review by congqixia — APPROVED** [review]
/lgtm
