### PR TITLE
Fix bulk insert may seal a failed importing segment

### LINKED ISSUE #21761: [Bug]: A import failed segment will be marked as Sealed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

image

A segment is under importing state, after one hour it is updated to Sealed State which make flush not working 

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xiaofan-luan**
fix #21761
Signed-off-by: xiaofan-luan <xiaofan.luan@zilliz.com>

### CODE REVIEW

File: internal/datacoord/segment_manager.go [hunk 1]
```diff
@@ -439,8 +442,7 @@ func (s *SegmentManager) SealAllSegments(ctx context.Context, collectionID Uniqu
 			ret = append(ret, id)
 			continue
 		}
-		if info.State == commonpb.SegmentState_Flushing ||
-			info.State == commonpb.SegmentState_Flushed {
+		if info.State != commonpb.SegmentState_Growing {
```
Comment (soothing-rain) [inline internal/datacoord/segment_manager.go:445]: The current design is that we manually altering a segment's state from `Importing` to `Sealed`, so bulk loading segment can be picked up by flush procedure just like other segments. This is done by calling `Flush` after task enters a `Persisted` state:
https://github.com/milvus-io/milvus/blob/master/internal/rootcoord/root_coord.go#L1806

So might wanna add Importing here as well.

Otherwise we should modify flush policy to catch `Importing` segments here:
https://github.com/milvus-io/milvus/blob/master/internal/datacoord/segment_allocation_policy.go#L186

Comment (soothing-rain) [inline internal/datacoord/segment_manager.go:445]: Also might need to update here as well:
https://github.com/milvus-io/milvus/blob/master/internal/datacoord/segment_manager.go#L528

File: internal/datacoord/segment_manager.go [hunk 2]
```diff
@@ -329,13 +329,17 @@ func isGrowing(segment *SegmentInfo) bool {
...
+func (s *SegmentManager) genExpireTs(ctx context.Context, isImported bool) (Timestamp, error) {
 	ts, err := s.allocator.allocTimestamp(ctx)
 	if err != nil {
 		return 0, err
 	}
 	physicalTs, logicalTs := tsoutil.ParseTS(ts)
 	expirePhysicalTs := physicalTs.Add(time.Duration(Params.DataCoordCfg.SegAssignmentExpiration.GetAsFloat()) * time.Millisecond)
+	// for imported segment, clean up ImportTaskExpiration
+	if isImported {
+		expirePhysicalTs = physicalTs.Add(time.Duration(Params.RootCoordCfg.ImportTaskExpiration.GetAsFloat()) * time.Millisecond)
```
Comment (soothing-rain) [inline internal/datacoord/segment_manager.go:341]: Should be `time.Second` here.

Also I found it inconsistent that sometimes we have both `second` and `millisecond` as time measurement in a lot of places in our `milvus.yaml` file
