### PR TITLE
Fix ParseSegmentIDBinlog panicks with bad input

### LINKED ISSUE #18412: [Bug]: ParseSegmentIDByBinlog panicks when input is not valid binlog path
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:9621b66
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`ParseSegmentIDByBinlog`panicks when input is not valid binlog path
with error message: "index out of range -2"

### Expected Behavior

utility function shall return error instead of panicking

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Fix #18412 

/kind bug

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

### CODE REVIEW

File: internal/storage/binlog_util.go [hunk 1]
```diff
@@ -1,12 +1,18 @@
...
 )
 
+// ParseSegmentIDByBinlog parse segment id from binlog paths
+// if path format is not expected, returns error
 func ParseSegmentIDByBinlog(path string) (UniqueID, error) {
-	// binlog path should consist of "files/insertLog/collID/partID/segID/fieldID/fileName"
+	// binlog path should consist of "[prefix]/insertLog/collID/partID/segID/fieldID/fileName"
 	keyStr := strings.Split(path, "/")
+	if len(keyStr) != 7 {
+		return 0, errors.New("invalid binlog path")
```
Comment (jaime0815) [inline internal/storage/binlog_util.go:15]: suggest output path within error log

Comment (congqixia) [reply internal/storage/binlog_util.go]: Fixed
