### PR TITLE
Fix deleted data is still visible

### LINKED ISSUE #23429: [Enhancement]: Support concurrent write delete records on QueryNode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

A delete buffer in QueryNode, also a sealed delete records. The delete buffer should be a map, so we are able to delete items in any order. The QueryNode merges the delete buffer into sealed delete records periodically , to improve the performance while applying delete

### Why is this needed?

Now QueryNode requires the delete records to be applied in order, and no concurrent write. This limits us to balance channel, also it's easy to make mistakes that breaks this limit. I'd like to remove this limitation

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yah01**
/kind bug
fix #23429 
related https://github.com/milvus-io/milvus/issues/24234
related #23726 
- trim overlapping prefix for coming delete records
- make all delete operations serialized to make sure they can calculate the overlapping correctly

This won't slow query/search down as query/search doesn't need to acquire the lock for delete op

### CODE REVIEW

**Comment by yah01** [comment]
Also, the sync (load) operation should inform the delegator to load delta logs to avoid it delivering delete records that are too "new"

File: internal/core/src/segcore/DeletedRecord.h [hunk 1]
```diff
@@ -76,15 +81,46 @@ struct DeletedRecord {
...
+        timestamps_.set_data_raw(n, timestamps + divide_point, size);
+        n_ += size;
+    }
+
+    int64_t
+    size() const {
+        return n_.load();
+    }
+
+    std::atomic<int64_t> n_ = 0;
```
Comment (jiaoew1991) [inline internal/core/src/segcore/DeletedRecord.h:115]: `n_` `timestamps_` `pks_` should be private ?

File: internal/querynodev2/segments/segment.go [hunk 2]
```diff
@@ -524,18 +524,18 @@ func (s *LocalSegment) preInsert(numOfRecords int) (int64, error) {
...
+// 		long int
+// 		PreDelete(CSegmentInterface c_segment, long int size);
+// 	*/
+// 	var offset C.int64_t
+// 	GetPool().Submit(func() (any, error) {
+// 		offset = C.PreDelete(s.ptr, C.int64_t(int64(numOfRecords)))
+// 		return nil, nil
+// 	}).Await()
+// 	return int64(offset)
+// }
```
Comment (XuanYang-cn) [inline internal/querynodev2/segments/segment.go:538]: maybe remove this
