### PR TITLE
fix: Add defer Unpin when error happens

### LINKED ISSUE #36619: [Bug]: Refcnt leaked when partition validation fails on querynodes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master(00a5025) & 2.4.12
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

 Refcnt leaked when partition validation fails on querynodes, which may cause deadlock when releasing segments

### Expected Behavior

Refcnt updated safely and no deadlock shall happen

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Resolves: #36619

### CODE REVIEW

File: internal/querynodev2/segments/validate.go [hunk 1]
```diff
@@ -62,6 +62,11 @@ func validate(ctx context.Context, manager *Manager, collectionID int64, partiti
 	// validate segment
 	segments := make([]Segment, 0, len(segmentIDs))
 	var err error
+	defer func() {
```
Comment (chyezh) [inline internal/querynodev2/segments/validate.go:65]:
```
err := fmt.Errorf("segment %d belongs to partition %d, which is not in %v", segment.ID(), segment.Partition(), searchPartIDs)
```
cannot assign the `err`.

Comment (congqixia) [reply internal/querynodev2/segments/validate.go:65]: nice catch, fixed
