### PR TITLE
Remove Load Delta Channel Request

### LINKED ISSUE #18393: [Bug]: Simply delta channel operation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

see #18391
When we do recover, we find several delta channel is not properly assigned with segment, causing system hang due to no time tick pushing forward.

### Expected Behavior

1. query coord should not assign delta channel
2. while querynode load segment, it handles delta channel load
3. TODO: release delta channel properly

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

1. currently delta channel is leaked due to not released, we will handle it later otherwise the delta channel will be consumed by every delta channel.

### PR DESCRIPTION
**Pull request by xiaofan-luan**
fix #18393
Remove watch Delta channel

Co-authored-by: congqixia <congqi.xia@zilliz.com>
Signed-off-by: xiaofan-luan <xiaofan.luan@zilliz.com>

### CODE REVIEW

File: internal/querynode/task.go [hunk 1]
```diff
@@ -545,38 +525,48 @@ func (l *loadSegmentsTask) PreExecute(ctx context.Context) error {
 }
 
 func (l *loadSegmentsTask) Execute(ctx context.Context) error {
-	// TODO: support db
 	log.Info("LoadSegmentTask Execute start", zap.Int64("msgID", l.req.Base.MsgID))
 	err := l.node.loader.LoadSegment(l.req, segmentTypeSealed)
 	if err != nil {
-		log.Warn(err.Error())
+		for _, segment := range l.req.Infos {
+			l.node.metaReplica.removeSegment(segment.SegmentID, segmentTypeSealed)
```
Comment (czs007) [inline internal/querynode/task.go:532]: When loadSegment returns an error (for example, a segment already exists), the original segment will be deleted during cleanup.

**Review by congqixia — APPROVED** [review]
/lgtm
