### PR TITLE
fix: the entities num metric may be contributed more than once

### LINKED ISSUE #29766: [Bug]: Entities Num metric not accurate
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master/2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

this metric shows more data than the system actually stored

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yah01**
the growing segments contribute to this metric while inserting and putting into the manager, but the current impl inserts data before putting the segments into manager, which leads to double contributions

fix: #29766

### CODE REVIEW

**Comment by samhuang-z** [comment]
rerun ut

File: internal/querynodev2/segments/segment_loader.go [hunk 1]
```diff
@@ -618,6 +618,14 @@ func (loader *segmentLoader) loadSegment(ctx context.Context,
 		}
 	}
 
+	metrics.QueryNodeNumEntities.WithLabelValues(
+		fmt.Sprint(paramtable.GetNodeID()),
+		fmt.Sprint(segment.Collection()),
+		fmt.Sprint(segment.Partition()),
+		segment.Type().String(),
+		fmt.Sprint(0),
```
Comment (congqixia) [inline internal/querynodev2/segments/segment_loader.go:626]: indexCountLabelName value is not correct

**Review by congqixia — APPROVED** [review]
/lgtm
