### PR TITLE
Let system panic if kv operation fail

### LINKED ISSUE #7126: Improve code atomicity and idempotency in rootcoord meta_table.go
#### What would you like to be added:
Improve code atomicity and idempotency in rootcoord meta_table.go

#### Why is this needed:
```
func (mt *metaTable) DeleteCollection(collID typeutil.UniqueID, ts typeutil.Timestamp, ddOpStr func(ts typeutil.Timestamp) (string, error)) error {
	mt.ddLock.Lock()
	defer mt.ddLock.Unlock()

	collMeta, ok := mt.collID2Meta[collID]
	if !ok {
		return fmt.Errorf("can't find collection. id = %d", collID)
	}

	delete(mt.collID2Meta, collID)
	delete(mt.collName2ID, collMeta.Schema.Name)

	// update segID2IndexMeta
	for partID := range collMeta.PartitionIDs {
		if segIDMap, ok := mt.partID2SegID[typeutil.UniqueID(partID)]; ok {
			for segID := range segIDMap {
				delete(mt.segID2IndexMeta, segID)
			}
		}
	}

    ... ...

	// save ddOpStr into etcd
	var saveMeta = map[string]string{}
	addition := mt.getAdditionKV(ddOpStr, saveMeta)
	err := mt.client.MultiSaveAndRemoveWithPrefix(saveMeta, delMetakeys, ts, addition)
	if err != nil {
		_ = mt.reloadFromKV()
		return err
	}

	return nil
}
```
For above code, if KV operation fail, the state of memory and etcd will be in-consistent.
Suggest to panic directly when KV operation fail.

### PR DESCRIPTION
**Pull request by cydrain**
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

Resolves: #7126

### CODE REVIEW

File: internal/rootcoord/meta_table.go [hunk 1]
```diff
@@ -200,7 +200,7 @@ func (mt *metaTable) AddTenant(te *pb.TenantMeta) (typeutil.Timestamp, error) {
 
 	ts, err := mt.client.Save(k, v)
 	if err != nil {
-		return 0, err
+		panic("SnapShotKV Save fail")
```
Comment (xiaofan-luan) [inline internal/rootcoord/meta_table.go:203]: including err message in panic, or log the error message before panic

**Comment by xiaofan-luan** [comment]
lgtm
