### PR TITLE
Fix segmentPtr concurrent visit and destroy

### LINKED ISSUE #19559: [Bug]: insert/delete/search is not safe with handoff release
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2f07344
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

insert/delete/search is not safe with handoff release

### Expected Behavior

Segment shall be safe to search with handoff release

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

Related to #19543

### PR DESCRIPTION
**Pull request by congqixia**
Fix #19559 
Related to #19543 

/kind bug

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

### CODE REVIEW

File: internal/querynode/segment.go [hunk 1]
```diff
@@ -249,11 +252,15 @@ func deleteSegment(segment *Segment) {
...
 
 func (s *Segment) getRealCount() int64 {
+	s.mut.RLock()
+	defer s.mut.RUnlock()
 	/*
 		int64_t
 		GetRealCount(CSegmentInterface c_segment);
 	*/
-	if s.segmentPtr == nil {
+	s.mut.RLock()
```
Comment (yah01) [inline internal/querynode/segment.go:261]: double lock

File: internal/querynode/segment.go [hunk 2]
```diff
@@ -115,56 +117,50 @@ func (s *Segment) getIDBinlogRowSizes() []int64 {
...
-		return fieldInfo.indexInfo != nil && fieldInfo.indexInfo.EnableIndex
+	fieldInfo, ok := s.indexedFieldInfos.Get(fieldID)
+	if !ok {
+		return false
 	}
+	return fieldInfo.indexInfo != nil && fieldInfo.indexInfo.EnableIndex
+}
 
-	return false
+func (s *Segment) healthy() bool {
```
Comment (yah01) [inline internal/querynode/segment.go:158]: We need comments to clarify that this method have to be called after hold `mut`
