### PR TITLE
Add e2e test for RESTful APIs, fix on proto_oneof fields

### LINKED ISSUE #17653: [Bug]: RESTful API request failed when contains protobuf's oneof type
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Return error when sends requests contains protobuf's oneof type, eg: create collection

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by haorenfsa**
Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com>
/cc @jennyli-z  @congqixia  @yanliang567 

Fix #17653

### CODE REVIEW

File: build/ci/jenkins/PR.groovy [hunk 1]
```diff
@@ -83,7 +83,7 @@ pipeline {
                     }
                     axis {
                         name 'MILVUS_CLIENT'
-                        values 'pymilvus'
```
Comment (jennyli-z) [inline build/ci/jenkins/PR.groovy:86]: 1. I prefer just run restful testing after orginal testing, so that we can only install milvus for once. Added here will double the resource (including install milvus standalone version, kafka version, pulsar version)
2. Probably add the testing in nightly first,  add it into pr when it is already running stable in nightly.
https://github.com/milvus-io/milvus/blob/master/build/ci/jenkins/Nightly.groovy#L173
@yanliang567  what do you think?

Comment (haorenfsa) [reply build/ci/jenkins/PR.groovy]: updated

**Comment by xiaofan-luan** [comment]
@haorenfsa  you need a issue related~

**Comment by xiaofan-luan** [comment]
Otherwise it all looks good to me
