### PR TITLE
#1234 do service check when Milvus startup

### LINKED ISSUE #1234: check s3 connection validation when Milvus startup
**Describe the bug**

storage_config:
  primary_path: /var/lib/milvus
  secondary_path:
  s3_enable: true
  s3_address: 127.0.0.1
  s3_port: 9000
  s3_access_key: xxxxxx
  s3_secret_key: xxxxxx
  s3_bucket: myminio

milvus log output:

```
2020-02-16 19:49:13,467 | ERROR | default | [STORAGE] ERROR: CreateBucket: : Unable to connect to endpoint
2020-02-16 19:49:45,901 | ERROR | default | [STORAGE] ERROR: PutObject: : Unable to connect to endpoint

```

**Steps/Code to reproduce behavior**
**Expected behavior**
**Environment details**
**Screenshots**
**Additional context**

### PR DESCRIPTION
**Pull request by cydrain**
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

**What type of PR is this?**
feature

**What this PR does / why we need it:**

**Which issue(s) this PR fixes:**
Fixes #1234

**Special notes for your reviewer:**
N/A

**Does this PR introduce a user-facing change?:**
No

**Additional documentation (e.g. design docs, usage docs, etc.):**
N/A

### CODE REVIEW

File: core/src/server/Server.cpp [hunk 1]
```diff
@@ -253,14 +252,33 @@ Server::LoadConfig() {
...
+        std::cerr << "knowhere resource initialize fail: " << stat.message() << std::endl;
+        return stat;
+    }
+
     scheduler::StartSchedulerService();
-    DBWrapper::GetInstance().StartService();
+
+    stat = DBWrapper::GetInstance().StartService();
+    if (!stat.ok()) {
+        std::cerr << "DBWrapper start service fail: " << stat.message() << std::endl;
```
Comment (JinHai-CN) [inline core/src/server/Server.cpp]: change to:
SERVER_LOG_ERROR << "DBWrapper start service fail: " << stat.message();
std::cerr << "Milvus initializes fail: " << stat.message() << std::endl;
