### PR TITLE
Fix may update the current target to an unavailable target when node down

### LINKED ISSUE #21696: [Bug]: QueryCoord may update the current target to an unavailable target when node down
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master/2.2.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

QueryCoord would pull a new next target when node down, as target observer is running and may pull next target too, and updates the current target to next-next target (which may be not available)

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
/kind bug
fix #21696 
Also add a method to safely update the next target

### CODE REVIEW

File: internal/querycoordv2/observers/target_observer.go [hunk 1]
```diff
@@ -175,4 +213,12 @@ func (ob *TargetObserver) updateCurrentTarget(collectionID int64) {
...
 		zap.Int64("collectionID", collectionID))
 	ob.targetMgr.UpdateCollectionCurrentTarget(collectionID)
+	notifiers := ob.readyNotifiers[collectionID]
+	for _, notifier := range notifiers {
+		close(notifier)
+	}
+	// Reuse the capacity of notifiers slice
+	if notifiers != nil {
+		ob.readyNotifiers[collectionID] = notifiers[:0]
+	}
```
Comment (congqixia) [inline internal/querycoordv2/observers/target_observer.go:223]: Ready notifies are not cleared when collection is removed

**Review by congqixia — APPROVED** [review]
/lgtm
Please fix comment issue of collection released corner case
