### PR TITLE
fix: text match panics when enable_match is set be false

### LINKED ISSUE #38949: [Bug]: text match panics when enable_match is set be false
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
  Master aa0a87eda728cb46cf777ab6ee1f7753de507577
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Panics when executing text match if enable_match is not True.

### Expected Behavior

Should return errors rather than panic.

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
fix: https://github.com/milvus-io/milvus/issues/38949

### CODE REVIEW

File: internal/parser/planparserv2/parser_visitor.go [hunk 1]
```diff
@@ -27,12 +27,15 @@ func (v *ParserVisitor) VisitParens(ctx *parser.ParensContext) interface{} {
...
 }
 
-func (v *ParserVisitor) translateIdentifier(identifier string) (*ExprWithType, error) {
+func (v *ParserVisitor) translateIdentifier(identifier string, requireEnableMatch bool) (*ExprWithType, error) {
 	identifier = decodeUnicode(identifier)
 	field, err := v.schema.GetFieldFromNameDefaultJSON(identifier)
 	if err != nil {
 		return nil, err
 	}
+	if requireEnableMatch && !typeutil.CreateFieldSchemaHelper(field).EnableMatch() {
```
Comment (czs007) [inline internal/parser/planparserv2/parser_visitor.go:36]: move this check to VisitTextMatch
