### PR TITLE
Phase 1 of implementation of read-write seperation

### LINKED ISSUE #4133: 0.11.x support read-write separation
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I started two milvus nodes， one writable node, one read-only node.  Metadata uses the same mysql, and map the same db directory.  the writable nodes can be used normally.  You can successfully connect to the read-only node, but when sending a request to the read-only node, such an error will occur:
image

image

### PR DESCRIPTION
**Pull request by XuPeng-SH**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #4133 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Review by wxyucs — DISMISSED** [review]

**Comment by JinHai-CN** [comment]
Comments are needed according our last meeting.

File: core/src/db/snapshot/SnapshotPolicy.cpp [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+}
+
+bool
+SnapshotNumPolicy::ShouldEject(const MapT& ids) {
+    bool should = true;
+    if (ids.size() <= num_) {
+        should = false;
+    }
+    return should;
+}
```
Comment (BossZou) [inline core/src/db/snapshot/SnapshotPolicy.cpp:29]: May can simplify to 'return (ids.size() > num_);'

**Review by BossZou — APPROVED** [review]

**Review by wxyucs — APPROVED** [review]
