### PR TITLE
Restful api error information

### LINKED ISSUE #25564: [Bug]: [restful]Insert with invalid db name, the error message is `code: CollectionNotExists, reason: can't find collection`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:PowderLi-2.2.0-dev-f08c363-20230712
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2023-07-13 15:39:01.903 | DEBUG    | api.milvus:logger_request_response:14 - method: post, url: http://10.100.36.162:19530/v1/vector/collections/create, cost time: 0.08318686485290527, header: {'Content-Type': 'application/json', 'Authorization': 'Bearer root:Milvus', 'RequestId': '55f3a41a-2150-11ee-a691-acde48001122'}, payload: {"collectionName": "test_collection2023_07_13_15_39_00", "dimension": 128}, response: {"code":200,"data":{}}
2023-07-13 15:39:01.946 | DEBUG    | api.milvus:logger_request_response:14 - method: get, url: http://10.100.36.162:19530/v1/vector/collections/describe, cost time: 0.04277682304382324, header: {'Content-Type': 'application/json', 'Authorization': 'Bearer root:Milvus', 'RequestId': '560086d0-2150-11ee-a691-acde48001122'}, payload: null, response: {"code":200,"data":{"collectionName":"test_collection2023_07_13_15_39_00","description":"","enableDynamic":true,"fields":[{"autoId":true,"description":"","name":"id","primaryKey":true,"type":"Int64"},...ription":"","name":"vector","primaryKey":false,"type":"FloatVector(128)"}],"indexes":[{"fieldName":"vector","indexName":"_default_idx_101","metricType":"L2"}],"load":"LoadStateLoading","shardsNum":2}}
2023-07-13 15:39:01.968 | INFO     | test_vector_operations:test_insert_vector_with_invalid_database_name:195 - body size: 0.031005859375 MB
2023-07-13 15:39:02.020 | ERROR    | api.milvus:logger_request_response:17 - method: post, url: http://10.100.36.162:19530/v1/vector/insert, cost time: 0.05042004585266113, header: {'Content-Type': 'application/json', 'Authorization': 'Bearer root:Milvus', 'RequestId': '560a7866-2150-11ee-a691-acde48001122'}, payload: {"collectionName": "test_collection2023_07_13_15_39_00", "data": [{"vector": [0.06049153179546981, 0.10062319534173296, 0.09809786912308963, 0.029772717860609484, 0.11821705146122621, 0.1487487591225434, 0.06710854939638869, 0.0814621098897029, 0.12510976104665208, 0.0025889163572342284, 0.043488508119024646, 0.013547728359841927, 0.14177679557348252, 0.043394396158212015, 0.01747085049650193, 0.09900477976418495, 0.005156482667037702, 0.014098549230662547, 0.0013704787557239613, 0.07842902965639163, 0.1143402179272544, 0.12155549644629667, 0.1110230167882976, 0.10352960552069847, 0.14446592050043067, 0.10264824499743834, 0.09034582493320661, 0.03664436488442783, 0.12248494844567748, 0.09698695215773627, 0.04013344712308833, 0.08811918056831401, 0.14766793049535765, 0.10877173740361601, 0.018588042119875695, 0.05203772074587824, 0.05746095981714932, 0.1357380765248194, 0.09072638980796795, 0.0008404755641628903, 0.1441298354174294, 0.1339163151178932, 0.03376331878155893, 0.06098484921...3892, 0.00160563252629778, 0.1036669984719359, 0.08770064444788939, 0.09272738305589256, 0.012763044189625783, 0.13823042002942365, 0.004807401336565996, 0.07271619691525323, 0.046635465659781605, 0.08580339363768504, 0.027472320540984044, 0.12775648977060333, 0.07144832973091483, 0.061918731592926386, 0.01818489094097056, 0.05598007882575725, 0.0803354463044589, 0.12978698339364983, 0.05964914254062493, 0.05644106959556526, 0.08061084588598308, 0.020773632677981557, 0.12853252149203112, 0.08447827217408801], "uid": 9, "name": "Joseph Robertson", "address": "625 Hughes Village Apt. 470\nNorth Jason, WV 87868", "text": "Just interview watch still treatment wear statement. Rule front eye fish happen. Crime group perform eye.", "email": "ggates@example.net", "phone_number": "(268)355-8108", "json": {"name": "Alex Shepard", "address": "2351 Neal Cliff\nPort Stevenville, TX 48739"}, "key87706": "value92803", "key30255": "value46787", "key96184": "value68424"}], "dbName": "invalid_database"}, response: {"code":1,"message":"code: CollectionNotExists, reason: can't find collection: test_collection2023_07_13_15_39_00"}
```

**response: {"code":1,"message":"code: CollectionNotExists, reason: can't find collection: test_collection2023_07_13_15_39_00"}**

### Expected Behavior

right error message is dbNmae is not exists

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### LINKED ISSUE #25629: [Bug]: [restful]Vector filed was not in output when outputFields is not set for query and get
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230716-a75cd134
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2023-07-17 11:03:44.028 | DEBUG    | api.milvus:logger_request_response:14 - method: post, url: http://10.101.141.252:19530/v1/vector/query, cost time: 0.12466287612915039, header: {'Content-Type': 'application/json', 'Authorization': 'Bearer root:Milvus', 'RequestId': '8a281b2a-244e-11ee-84dd-acde48001122'}, payload: {"collectionName": "test_collection2023_07_17_11_03_29", "filter": "uid > 0", "limit": 100, "offset": 0}, response: {"code":200,"data":[{"address":"02627 Schmidt Square\nNorth Roberthaven, CT 75269","email":"valeriepearson@example.net","id":442908018027277380,"json":{"address":"48366 Billy Flats Apt. 273\nJackshire...6","text":"Just one class conference room food conference same. Professor happen control beyond college ahead. Movie life threat rule.\nSure American reach school. Blue seek test certain.","uid":99}]}
2023-07-17 11:03:44.030 | INFO     | test_vector_operations:test_query_vector_with_int64_filter:631 - res: 99
FAILED
testcases/test_vector_operations.py:595 (TestQueryVector.test_query_vector_with_int64_filter[False-False-uid > 00])
'vector' != {'address': '02627 Schmidt Square\nNorth Roberthaven, CT 75269',
 'email': 'valeriepearson@example.net',
 'id': 442908018027277380,
 'json': {'address': '48366 Billy Flats Apt. 273\nJackshire, NY 19356',
          'name': 'Jeremy Vega'},
 'key29269': 'value81458',
 'key38447': 'value57042',
 'key5549': 'value92566',
 'key57902': 'value669',
 'key65755': 'value967',
 'key72548': 'value23550',
 'key86839': 'value49120',
 'name': 'Christina Ortega',
 'phone_number': '001-474-716-1840x1045',
 'text': 'Area feel career right gun she source. Maintain center form enjoy.\n'
         'Politics partner institution inside inside. Believe ground this '
         'increase different.',
 'uid': 1}
```

### Expected Behavior

vector field should also be in output when outputFileds is not set

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PowderLi**
/kind bug
fix #25564
fix #25629
bring by #24761

### CODE REVIEW

File: internal/distributed/proxy/httpserver/handler_v1.go [hunk 1]
```diff
@@ -331,18 +372,35 @@ func (h *Handlers) query(c *gin.Context) {
...
+	if req.OutputFields == nil {
+		req.OutputFields = []string{DefaultOutputFields}
+		coll, err := h.describeCollection(c, httpReq.DbName, httpReq.CollectionName, false)
+		if err != nil || coll == nil {
+			return
+		}
+		for _, field := range coll.Schema.Fields {
+			if field.DataType == schemapb.DataType_BinaryVector || field.DataType == schemapb.DataType_FloatVector {
+				req.OutputFields = append(req.OutputFields, field.Name)
+				break
```
Comment (jaime0815) [inline internal/distributed/proxy/httpserver/handler_v1.go:390]: we'd better append all matched vector fields.

File: internal/distributed/proxy/httpserver/handler_v1.go [hunk 2]
```diff
@@ -351,49 +409,63 @@ func (h *Handlers) query(c *gin.Context) {
...
+	if err != nil {
+		c.JSON(http.StatusOK, gin.H{HTTPReturnCode: merr.Code(merr.ErrCheckPrimaryKey), HTTPReturnMessage: merr.ErrCheckPrimaryKey.Error()})
 		return
 	}
+	req.Expr = filter
+	if req.OutputFields == nil {
+		req.OutputFields = []string{DefaultOutputFields}
+		for _, field := range coll.Schema.Fields {
+			if field.DataType == schemapb.DataType_BinaryVector || field.DataType == schemapb.DataType_FloatVector {
+				req.OutputFields = append(req.OutputFields, field.Name)
```
Comment (jaime0815) [inline internal/distributed/proxy/httpserver/handler_v1.go:454]: we'd better append all matched fields.
