### PR TITLE
Fix s3 delete file failed when not enable object lock

### LINKED ISSUE #17573: Delete index file failed from S3
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: directly access s3 by minio
```

### Current Behavior

[\"IndexCoord recycleUnusedIndexFiles Remove index files failed\"] [MarkDeleted=true] [error=\"x-amz-bypass-governance-retention is only applicable to Object Lock enabled buckets.

It seems to use the default retention governance mode, which causes delete fail.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by haorenfsa**
Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com> 
Fix #17573
/cc @LoveEachDay @jaime0815

### CODE REVIEW

File: internal/storage/minio_chunk_manager.go [hunk 1]
```diff
@@ -286,7 +286,16 @@ func (mcm *MinioChunkManager) MultiRemove(keys []string) error {
 // RemoveWithPrefix removes all objects with the same prefix @prefix from minio.
 func (mcm *MinioChunkManager) RemoveWithPrefix(prefix string) error {
 	objects := mcm.Client.ListObjects(mcm.ctx, mcm.bucketName, minio.ListObjectsOptions{Prefix: prefix, Recursive: true})
-	for rErr := range mcm.Client.RemoveObjects(mcm.ctx, mcm.bucketName, objects, minio.RemoveObjectsOptions{GovernanceBypass: true}) {
+	mode, _, _, err := mcm.Client.GetBucketObjectLockConfig(mcm.ctx, mcm.bucketName)
```
Comment (jaime0815) [inline internal/storage/minio_chunk_manager.go:289]: We can delete GovernanceBypass config directly,  it should not be a backward compatibility issue.

Comment (haorenfsa) [reply internal/storage/minio_chunk_manager.go:289]: Is there any user already using S3 with object lock? I don't know. It's your calls anyway.

Comment (LoveEachDay) [reply internal/storage/minio_chunk_manager.go:289]: It's better to keep this object lock check.

Comment (jaime0815) [reply internal/storage/minio_chunk_manager.go:289]: we will not consider backward compatibility because the data should be granted modification privilege, or it is against data process flow within Milvus.

Comment (jaime0815) [reply internal/storage/minio_chunk_manager.go:289]: enable object means both compaction and delete will fail.

Comment (haorenfsa) [reply internal/storage/minio_chunk_manager.go]: Updated
