### PR TITLE
Refine QueryCoord stopping

### LINKED ISSUE #27392: [Enhancement]: Stopping QueryCoord gracefully
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The QueryCoord stops its components in an arbitrary order, this may break the dependency while stopping, some received requests would fail.

We need to stop these components carefully, to keep the service working well during upgrading

### Why is this needed?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yah01**
/kind improvement
resolve #27392

### CODE REVIEW

File: internal/querycoordv2/observers/collection_observer.go [hunk 1]
```diff
@@ -67,35 +66,36 @@ func NewCollectionObserver(
...
-			case <-ob.stopCh:
 				log.Info("CollectionObserver stopped")
 				return
 
 			case <-ticker.C:
-				ob.Observe()
+				ob.Observe(ctx)
 			}
 		}
 	}()
```
Comment (congqixia) [inline internal/querycoordv2/observers/collection_observer.go:87]: Need a `waitgroup` for collection observer worker lifetime control

**Review by congqixia — APPROVED** [review]
/lgtm
