### PR TITLE
Close kafka internal consumer&producer properly

### LINKED ISSUE #24996: [Bug]: Kafka Consumer is not closed properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2176907(master) & af313ba(2.2)
- Deployment mode(standalone or cluster): both
- MQ type(rocksmq, pulsar or kafka):  kafka  
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

``` go
func (kc *Consumer) Close() {
	kc.closeOnce.Do(func() {
		close(kc.closeCh)
	})
}
```
This previous code, the consumer is not closed while worker may be still running

### Expected Behavior

All kafka consumer shall be closed safely after Close return.

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

Related to #24970

### PR DESCRIPTION
**Pull request by congqixia**
Resolves #24996 
Related to #24970
/kind bug

### CODE REVIEW

File: internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go [hunk 1]
```diff
@@ -116,7 +117,9 @@ func (kc *Consumer) Chan() <-chan mqwrapper.Message {
 		panic("failed to chan a kafka consumer without assign")
 	}
 	kc.chanOnce.Do(func() {
+		kc.wg.Add(1)
 		go func() {
+			defer kc.wg.Done()
 			for {
 				select {
 				case <-kc.closeCh:
```
Comment (jaime0815) [inline internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go:125]: it doesn't need to wait for the closing goroutine to finish, because the close is an async operation for the consumer.

Comment (congqixia) [reply internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go:125]: will it be a problem that the legacy goroutine still calling `kc.c.ReadMessage` while internal client is closed?

Comment (congqixia) [reply internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go:125]: yes, but it could happen that close client happens first, and ReadMessage still in progress. This waitgroup is meant to prevent this situation
