### PR TITLE
IP search metric_type shouldn't be supported by IVF_PQ index on GPU v…

### LINKED ISSUE #616: IP search metric_type is not supported by IVF_PQ index
**Describe the bug**
message returned is not right

```
2019-11-29 16:26:29,608 | ERROR | default | [WRAPPER] Error in void faiss::gpu::GpuIndexIVFPQ::verifySettings_() const at gpu/GpuIndexIVFPQ.cu:450: Error: 'this->metric_type == faiss::METRIC_L2' failed: METRIC_INNER_PRODUCT is currently unsupported
2019-11-29 16:26:29,608 | ERROR | default | [ENGINE] BuildIndex encounter exception: Error in void faiss::gpu::GpuIndexIVFPQ::verifySettings_() const at gpu/GpuIndexIVFPQ.cu:450: Error: 'this->metric_type == faiss::METRIC_L2' failed: METRIC_INNER_PRODUCT is currently unsupported
2019-11-29 16:26:29,610 | ERROR | default | [ENGINE] Failed to build index, index file is too large or gpu memory is not enough
2019-11-29 16:26:29,610 | ERROR | default | [ENGINE] Building index job 1424 failed: Error: BuildIndex encounter exception: Error in void faiss::gpu::GpuIndexIVFPQ::verifySettings_() const at gpu/GpuIndexIVFPQ.cu:450: Error: 'this->metric_type == faiss::METRIC_L2' failed: METRIC_INNER_PRODUCT is currently unsupported
2019-11-29 16:26:29,974 | ERROR | default | [SERVER] Request failed with code: Error: Failed to build index for 1 file, file size is too large or gpu memory is not enough.

```

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
0.6.0-GPU

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Yukikaze-CZR**
This fix #616 #636.
If metric_type is IP, index IVF_PQ can only be built on CPU version but cannot be built on CPU version. However, index IVF_PQ can be built on CPU version and searched on GPU version.

### CODE REVIEW

File: core/src/wrapper/gpu/GPUVecImpl.cpp [hunk 1]
```diff
@@ -16,6 +16,7 @@
 // under the License.
 
 #include "wrapper/gpu/GPUVecImpl.h"
+#include <src/wrapper/WrapperException.h>
```
Comment (fishpenguin) [inline core/src/wrapper/gpu/GPUVecImpl.cpp]: #include "wrapper/WrapperException.h"

File: core/src/wrapper/gpu/GPUVecImpl.cpp [hunk 2]
```diff
@@ -58,6 +59,7 @@ IVFMixIndex::BuildAll(const int64_t& nb, const float* xb, const int64_t* ids, co
         }
     } catch (knowhere::KnowhereException& e) {
         WRAPPER_LOG_ERROR << e.what();
+        throw WrapperException(e.what());
         return Status(KNOWHERE_UNEXPECTED_ERROR, e.what());
```
Comment (fishpenguin) [inline core/src/wrapper/gpu/GPUVecImpl.cpp]: Remove return?

**Review by fishpenguin — APPROVED** [review]
