### PR TITLE
fix: enable to build index with single segment

### LINKED ISSUE #39232: [Bug]: support building tantivy index with single segment based on config
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment
```
- Milvus version: 2.5
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Some old milvus version can only recognize tantivy index with single segment while master only build tantivy index with multi segments. In some situations, query node which loads the tantivy index can be the old version while the index buliding node can be the new version. 

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
fix https://github.com/milvus-io/milvus/issues/39232

### CODE REVIEW

File: internal/core/src/indexbuilder/ScalarIndexCreator.cpp [hunk 1]
```diff
@@ -30,6 +30,9 @@ ScalarIndexCreator::ScalarIndexCreator(
     if (config.contains("index_type")) {
         index_type_ = config.at("index_type").get<std::string>();
     }
+    if (config.contains("inverted_list_single_segment")) {
```
Comment (czs007) [inline internal/core/src/indexbuilder/ScalarIndexCreator.cpp:33]: inverted_index_single_segment

File: internal/core/src/index/InvertedIndexTantivy.cpp [hunk 2]
```diff
@@ -416,16 +417,34 @@ InvertedIndexTantivy<T>::BuildWithRawData(size_t n,
     boost::filesystem::create_directories(path_);
     d_type_ = get_tantivy_data_type(schema_);
     std::string field = "test_inverted_index";
+    if (config.contains("inverted_list_single_segment")) {
+        inverted_list_single_segment_ = true;
```
Comment (zhagnlu) [inline internal/core/src/index/InvertedIndexTantivy.cpp:421]: make "inverted_list_single_segment" a const variable like MMAP_FILE_PATH, and all using variable instead is better

**Comment by xiaocai2333** [comment]
rerun go-sdk
