### PR TITLE
Fix #1298

### LINKED ISSUE #1298: Unittest failed on CPU2GPU case
**Describe the bug**
Here is CI log output:
```
[2020-02-21T06:57:30.860Z] [ RUN      ] WrapperParam/KnowhereWrapperTest.TO_GPU_TEST/5

[2020-02-21T06:57:31.432Z] 

[2020-02-21T06:57:31.432Z] Precision: 1, match: 100, total: 100

[2020-02-21T06:57:31.432Z] unknown file: Failure

[2020-02-21T06:57:31.432Z] C++ exception with description "Error in knowhere::VectorIndexPtr knowhere::cloner::CopyCpuToGpu(const VectorIndexPtr&, const int64_t&, const Config&) at Cloner.cpp:54: this index type not support tranfer to gpu" thrown in the test body.

[2020-02-21T06:57:31.432Z] [  FAILED  ] WrapperParam/KnowhereWrapperTest.TO_GPU_TEST/5, where GetParam() = (4-byte object <0F-00 00-00>, "Default", 64, 10000, 10, 10) (384 ms)
```

More details can be found [here](http://internal.zilliz.com:18080/jenkins/blue/organizations/jenkins/milvus-ci/detail/PR-1287/5/pipeline)

### PR DESCRIPTION
**Pull request by tinkerlin**
Signed-off-by: xiaojun.lin <xiaojun.lin@zilliz.com>

**What type of PR is this?**
Bug fix

**What this PR does / why we need it:**
/

**Which issue(s) this PR fixes:**
Fixes #1298
 
**Special notes for your reviewer:**
/

**Does this PR introduce a user-facing change?:**
/

**Additional documentation (e.g. design docs, usage docs, etc.):**
/

### CODE REVIEW

File: core/unittest/wrapper/test_wrapper.cpp [hunk 1]
```diff
@@ -154,6 +154,9 @@ TEST_P(KnowhereWrapperTest, BASE_TEST) {
 
 #ifdef MILVUS_GPU_VERSION
 TEST_P(KnowhereWrapperTest, TO_GPU_TEST) {
+	if (index_type == milvus::engine::IndexType::HNSW) {
```
Comment (cydrain) [inline core/unittest/wrapper/test_wrapper.cpp]: please fix clang format

Comment (tinkerlin) [reply core/unittest/wrapper/test_wrapper.cpp]: clang-format check pass

**Review by cydrain — APPROVED** [review]
