### PR TITLE
Refine compareAndSwap interface in etcdKV

### LINKED ISSUE #18066: [Bug]: Etcd compareAndSwap should not throw err if compare condition does not match
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Currently, in etcd kv CompareVersionAndSwap interface, if we compare condition does not match, we will hit NewCompareFailedError.

### Expected Behavior

we should return both boolean(whether compare and set success) and err (will be nil the command executed successfully )

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xiaofan-luan**
fix #18066 
1. change the etcd compareAndSwap interface
2. fix the case datanode leak flowgraph
3. fix the case indexnode write meaning less etcd path

Signed-off-by: xiaofan-luan <xiaofan.luan@zilliz.com>

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
datanode part lgtm

**Comment by xiaofan-luan** [comment]
related to #17958

File: internal/indexcoord/meta_table.go [hunk 1]
```diff
@@ -42,8 +42,8 @@ import (
 // revision: The number of times IndexMeta has been changed in etcd. It's the same as Event.Kv.Version in etcd.
 // indexMeta: A structure that records the state of the index defined by proto.
 type Meta struct {
-	indexMeta *indexpb.IndexMeta
-	revision  int64
+	indexMeta    *indexpb.IndexMeta
+	indexVersion int64
```
Comment (czs007) [inline internal/indexcoord/meta_table.go:46]: Misunderstanding. It will be changed in the next PR. The `revision` here corresponds to the version of the key in etcd.
What you want to change is actually the Version in indexpb.
