### PR TITLE
fix: build text index when loading field data

### LINKED ISSUE #38644: [Bug]: TEXT_MATCH returning no results sometimes.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.5.0-gpu
- Deployment mode(standalone or cluster): Standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.5.0
- OS(Ubuntu or CentOS): MacOS and linux
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

After uploading the documents in milvus, I query with client.search and filter = f"TEXT_MATCH(content, '{important_words}')".
The first query goes well, then even trying with the same query it returns no results.

### Expected Behavior

_No response_

### Steps To Reproduce

[UPDATED]

Start Milvus on Docker

Create a collection with 

            COLLECTION_NAME = "Documents"
            EMBEDDING_DIM = 768
            analyzer_params = {
                    "type": "standard",
                    "filter": ["lowercase"],
                    }

            fields = [
                FieldSchema(name="id", dtype=DataType.INT64, max_length=100, is_primary=True),
                FieldSchema(name="content", dtype=DataType.VARCHAR, max_length=10000, enable_analyzer=True, analyzer_params=analyzer_params, enable_match=True),
                FieldSchema(name="file_id", dtype=DataType.VARCHAR, max_length=100),
                FieldSchema(name="file_name", dtype=DataType.VARCHAR, max_length=255),
                FieldSchema(name="page_num", dtype=DataType.INT64),
                FieldSchema(name="para_num", dtype=DataType.INT64),
                FieldSchema(name="data_type", dtype=DataType.VARCHAR, max_length=50),
                FieldSchema(name="company_name", dtype=DataType.VARCHAR, max_length=255),
                FieldSchema(name="file_path", dtype=DataType.VARCHAR, max_length=100),
                FieldSchema(name="folder_name", dtype=DataType.VARCHAR, max_length=255),
                FieldSchema(name="created_date", dtype=DataType.VARCHAR, max_length=50),
                FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=EMBEDDING_DIM),
                FieldSchema(name="sparse_embeddings", dtype=DataType.SPARSE_FLOAT_VECTOR)
            ]

            try:
                schema = CollectionSchema(fields, description="Document collection", auto_id=True, enable_dynamic_field=True)
                collection = Collection(COLLECTION_NAME, schema)
                # Create an index on the dense embedding field

                try:
                    dense_index_params = {
                        "index_type": "IVF_FLAT",  # Choose an appropriate index type (e.g., IVF_FLAT)
                        "metric_type": "COSINE",   # Metric type (e.g., COSINE for cosine similarity)
                        "params": {"nlist": 128}   # Index parameters
                    }

                    collection.create_index(field_name="embedding", index_params=dense_index_params)
                except Exception as e:
                    print(e)

                try:
                    # Create an index on the sparse embedding field
                    sparse_index_params = {
                        "index_type": "SPARSE_INVERTED_INDEX",
                        "metric_type": "IP",  # Inner Product is supported for sparse vectors
                        "params": {"drop_ratio_build": 0.2}  # Parameters specific to sparse indexing
                    }

                    collection.create_index(field_name="sparse_embeddings", index_params=sparse_index_params)

                    logger.info(f"Indexes created successfully")

                except Exception as e:
                    logger.error(f"Error while creating Indexes: {e}")
            except Exception as e:
                logger.error(f"Error while creating Schema: {e}")

ONLY CREATE COLLECTION IF the password is not updated, so one time only.

Load documents inside the collection, and try the TEXT_MATCH filter. At this stage, it works normally.

Remove the container and rebuild it. Now, the collection and the documents are still in the volume, so it doesn't create a new one.

Try the TEXT_MATCH filter, it doesn't find any results, while the normal semantic search does.

The only solution I've found is to delete all the volumes, recreate the collection, and reinsert the documents.

### Milvus Log

_No response_

### Anything else?

_No response_

### LINKED ISSUE #39053: [Bug]: TempIndex failed to process the data already persisted within the growing segment.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:Master & 2.5 & 2.4
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

We have two types of growing segments:
1) Data located after the shard leader's consumption checkpoint, where the shard leader will consume the first message of the segment, then create the growing segment. This is not an issue, and subsequent inserts will be directed to TempIndex.
2) Data that is entirely or partially located before the shard leader's checkpoint (meaning some of it has already been committed to object storage). This segment is created during the invocation of the watch channel for the shard leader, specifying the segment ID and data path.   The data within these files needs to be integrated into the temporary index.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
fix: https://github.com/milvus-io/milvus/issues/39053
may fix https://github.com/milvus-io/milvus/issues/38644 which could be caused by https://github.com/milvus-io/milvus/issues/39053

### CODE REVIEW

File: internal/core/src/segcore/SegmentGrowingImpl.cpp [hunk 1]
```diff
@@ -274,6 +274,15 @@ SegmentGrowingImpl::LoadFieldData(const LoadFieldDataInfo& infos) {
                 storage::GetByteSizeOfFieldDatas(field_data));
         }
 
+        // build text match index
+        if (field_meta.enable_match()) {
+            auto index = GetTextIndex(field_id);
```
Comment (zhagnlu) [inline internal/core/src/segcore/SegmentGrowingImpl.cpp:279]: can get index at this interface ? index not build before ?

File: internal/core/src/index/TextMatchIndex.cpp [hunk 2]
```diff
@@ -198,6 +198,18 @@ TextMatchIndex::AddTexts(size_t n,
...
 
+void
+TextMatchIndex::BuildIndexFromFieldData(
+    const std::vector<FieldDataPtr>& field_datas) {
+    int64_t offset = 0;
+    for (const auto& data : field_datas) {
+        auto n = data->get_num_rows();
+        wrapper_->add_data(
+            static_cast<const std::string*>(data->Data()), n, offset);
+        offset += n;
```
Comment (zhagnlu) [inline internal/core/src/index/TextMatchIndex.cpp:209]: no need to consider nullable ?

File: internal/core/src/segcore/SegmentGrowingImpl.cpp (hunk 1 above)
Comment (SpadeA-Tang) [reply internal/core/src/segcore/SegmentGrowingImpl.cpp:279]: index is created when at the constructor of SegmentGrowingImpl

File: internal/core/src/index/TextMatchIndex.cpp (hunk 2 above)
Comment (SpadeA-Tang) [reply internal/core/src/index/TextMatchIndex.cpp:209]: Good catch.
