### PR TITLE
Compaction bypass stale segments

### LINKED ISSUE #20201: [Bug]: Continuous Compaction may cause result segment checkpoint freezed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:48f5c60
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Continuous Compaction may cause result segment checkpoint freezed

### Expected Behavior

When compaction happens a lot, segments cp point shall still be able to proceed

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

Related to Datanode memory issue after restart in #19526

### PR DESCRIPTION
**Pull request by congqixia**
Fix #20201 
See also #19526 

/kind improvement

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

### CODE REVIEW

File: internal/datacoord/compaction_trigger.go [hunk 1]
```diff
@@ -449,6 +449,11 @@ func (t *compactionTrigger) generatePlans(segments []*SegmentInfo, force bool, c
 	// TODO, currently we lack of the measurement of data distribution, there should be another compaction help on redistributing segment based on scalar/vector field distribution
 	for _, segment := range segments {
 		segment := segment.ShadowClone()
+		// by-pass stale segments
+		if !force && t.isStaleSegment(segment) {
+			log.Debug("generate plans skip stale segment", zap.Int64("segmentID", segment.GetID()), zap.Time("lastFlushTime", segment.lastFlushTime))
```
Comment (jiaoew1991) [inline internal/datacoord/compaction_trigger.go:454]: the log level is correct?

Comment (congqixia) [reply internal/datacoord/compaction_trigger.go:454]: This log could be very frequent in some case, so put it in debug level. Which level you have in mind? @jiaoew1991
