### PR TITLE
Clear collection meta after all channels/segments released

### LINKED ISSUE #25209: [Bug]: Stale collection object in querynode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Presently, within the query node, collection objects shall persist indefinitely even when a user releases a collection. However, metrics associated with the collection object may have alterations after reloading. For example:
1. metricType
image

2. CollectionIndexMeta
image

### Expected Behavior

We are presented with two alternatives:
1. Manually assign the `metricType` and `CollectionIndexMeta` each time reloading occurs.
2. Properly remove the collection object.

In my personal preference, I lean towards the latter option.

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yah01**
/kind bug
fix #25209

### CODE REVIEW

File: internal/querynodev2/services.go [hunk 1]
```diff
@@ -444,7 +446,7 @@ func (node *QueryNode) LoadPartitions(ctx context.Context, req *querypb.LoadPart
 	if err != nil {
 		return merr.Status(err), nil
 	}
-	node.manager.Collection.Put(req.GetCollectionID(), req.GetSchema(), &segcorepb.CollectionIndexMeta{
+	node.manager.Collection.PutOrRef(req.GetCollectionID(), req.GetSchema(), &segcorepb.CollectionIndexMeta{
```
Comment (congqixia) [inline internal/querynodev2/services.go:449]: This `PurOrRef` will make refcount never be 0

**Review by congqixia — CHANGES_REQUESTED** [review]

File: internal/querynodev2/services.go [hunk 2]
```diff
@@ -637,7 +592,8 @@ func (node *QueryNode) ReleaseSegments(ctx context.Context, req *querypb.Release
 
 	log.Info("start to release segments")
 	for _, id := range req.GetSegmentIDs() {
-		node.manager.Segment.Remove(id, req.GetScope())
+		_, sealedCount := node.manager.Segment.Remove(id, req.GetScope())
+		node.manager.Collection.Unref(req.GetCollectionID(), uint32(sealedCount))
```
Comment (congqixia) [inline internal/querynodev2/services.go:596]: why not sum and unref in one call?

**Review by congqixia — APPROVED** [review]
/lgtm
